import React,{useEffect,useRef,useState}from"react";
import{useCall}from"../../context/CallContext";
import CallMemberInvite from"./CallMemberInvite";
import"./calls.css";
import"./callRecovery.css";
import"../collaborators/collaborators.css";

const duration=value=>`${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`;
const contextLabel=value=>({direct:"Direct conversation",repository:"Repository conversation",issue:"Issue conversation",pull_request:"Pull request conversation",mentor:"Mentor session",guided_contribution:"Guided contribution"}[value.callType]||"CodeHub conversation");
function Video({stream,muted,label}){const ref=useRef(null);useEffect(()=>{if(ref.current)ref.current.srcObject=stream||null;},[stream]);return <figure className="call-video"><video ref={ref} autoPlay playsInline muted={muted}/><figcaption>{label}</figcaption></figure>;}
function Status({call}){return call.error?<p className="call-status" role="alert">{call.error}<button type="button" aria-label="Dismiss call message" onClick={call.clearError}>Dismiss</button></p>:null;}

export default function CallOverlay(){
  const call=useCall(),[settings,setSettings]=useState(false),dialog=useRef(null);
  useEffect(()=>{if(call?.incoming||call?.call)dialog.current?.focus();},[call?.incoming,call?.call]);
  if(!call)return null;
  if(call.incoming)return <div className="call-backdrop"><section className="incoming-call" role="dialog" aria-modal="true" aria-live="assertive" tabIndex="-1" ref={dialog}><p>Incoming {call.incoming.mediaMode} call</p><h2>{call.incoming.initiatedBy?.name||call.incoming.initiatedBy?.username||"CodeHub user"}</h2><p>{call.incoming.repository?.name||call.incoming.callType.replaceAll("_"," ")}</p><div><button disabled={call.checking} onClick={()=>call.accept(true)}>Accept</button>{call.incoming.mediaMode==="video"&&<button disabled={call.checking} onClick={()=>call.accept(false)}>Accept without video</button>}<button disabled={call.checking} onClick={call.reject}>Reject</button></div><Status call={call}/></section></div>;
  if(!call.call&&call.recovery)return <section className="call-recovery" aria-live="polite"><div><strong>You have an active call.</strong><span>{call.recovery.mediaMode} call · {call.recovery.status}</span><span>Context: {contextLabel(call.recovery)}</span><time dateTime={call.recovery.startedAt}>{new Date(call.recovery.startedAt||call.recovery.createdAt).toLocaleString()}</time></div><div><button type="button" disabled={call.checking} onClick={call.rejoin}>{call.recovery.status==="ringing"?"Return to outgoing call":"Rejoin call"}</button><button type="button" disabled={call.checking} onClick={call.leaveRecovery}>{call.recovery.status==="ringing"?"Cancel call":"Leave call"}</button><button type="button" disabled={call.checking} onClick={call.refreshActive}>Refresh state</button></div><Status call={call}/></section>;
  if(!call.call)return <Status call={call}/>;
  const remotes=Object.entries(call.remoteStreams);
  return <div className="call-backdrop"><section className="active-call" role="dialog" aria-modal="true" aria-label="Active CodeHub call" tabIndex="-1" ref={dialog}><header><div><strong>{call.call.callType.replaceAll("_"," ")} call</strong><span>{duration(call.elapsed)}</span></div><span aria-live="polite">Network: {call.reconnecting?"reconnecting":call.quality}</span></header><div className="call-stage">{remotes.length?remotes.map(([id,stream])=><Video key={id} stream={stream} label={`Participant ${id.slice(-4)}`}/>):<p>Waiting for media…</p>}<Video stream={call.localStream} muted label="You"/></div><aside><h3>Participants ({call.call.participants?.length||1}/{call.call.maxParticipants||4})</h3>{call.call.participants?.map(value=><p key={value.user?._id||value.user}>{value.user?.username||"Participant"}{value.microphoneEnabled===false?" · muted":""}{value.cameraEnabled===false?" · camera off":""}{value.handRaised?" · hand raised":""}</p>)}{call.call.maxParticipants>2&&<CallMemberInvite key={call.call._id} activeCall={call.call} invite={call.invite}/>}</aside>{settings&&<div className="call-settings"><label>Microphone<select onChange={event=>call.selectDevice("audioinput",event.target.value)}>{call.devices.filter(value=>value.kind==="audioinput").map(value=><option key={value.deviceId} value={value.deviceId}>{value.label||"Microphone"}</option>)}</select></label><label>Camera<select onChange={event=>call.selectDevice("videoinput",event.target.value)}>{call.devices.filter(value=>value.kind==="videoinput").map(value=><option key={value.deviceId} value={value.deviceId}>{value.label||"Camera"}</option>)}</select></label></div>}<footer><button onClick={call.toggleMicrophone}>Microphone</button><button onClick={call.toggleCamera}>Camera</button><button onClick={call.call.screenSharing?call.stopScreen:call.shareScreen}>{call.call.screenSharing?"Stop sharing":"Share screen"}</button><button onClick={call.toggleHand}>{call.call.localHandRaised?"Lower hand":"Raise hand"}</button><button onClick={()=>{call.loadDevices();setSettings(value=>!value);}}>Devices</button><button onClick={async()=>{const video=document.querySelector(".call-stage video:not([muted])");if(!video?.requestPictureInPicture)throw new Error("Picture-in-picture is not supported by this browser.");await video.requestPictureInPicture();}}>Picture in picture</button><button className="call-end" onClick={call.end}>{call.call.status==="ringing"?"Cancel call":"End call"}</button></footer><Status call={call}/></section></div>;
}
