import React,{useMemo,useRef,useState}from"react";
import{useAuth}from"../../authContext";
import{getRepositoryCallMembers}from"../../services/callApi";

const idOf=value=>String(value?.userId||value?.user?._id||value?.user?.id||value?.user||value?._id||value?.id||value||"");
const roleLabel=value=>String(value||"member").split("_").map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(" ");
const invitationMessage=error=>({CALL_MEMBER_NOT_FOUND:"Repository member not found.",CALL_MEMBER_INACTIVE:"This user no longer has active repository access.",CALL_MEMBER_ACCESS_EXPIRED:"This user's temporary repository access has expired.",CALL_ALREADY_PARTICIPANT:"This user is already in the call.",CALL_ALREADY_INVITED:"This user has already been invited.",CALL_PARTICIPANT_LIMIT:"This call has reached the four-participant limit.",CALL_FORBIDDEN:"You do not have permission to invite participants.",CALL_NOT_ACTIVE:"This call is no longer accepting invitations."}[error?.code]||"The invitation could not be sent. Try again.");

export default function CallMemberInvite({activeCall,invite}){
  const auth=useAuth(),authUser=auth?.currentUser||auth?.user||auth?.authenticatedUser||null,selfId=idOf(authUser),repositoryId=idOf(activeCall.repository),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[members,setMembers]=useState([]),[search,setSearch]=useState(""),[selected,setSelected]=useState(""),[sending,setSending]=useState(false),[message,setMessage]=useState(null),requestRef=useRef(0);
  const participantFromList=(activeCall.participants||[]).find(participant=>idOf(participant)===selfId),currentParticipant=activeCall.currentParticipant||participantFromList||null;
  const participantRole=String(currentParticipant?.role||"").toLowerCase(),participantStatus=String(currentParticipant?.status||"").toLowerCase(),initiatedByCurrentUser=Boolean(selfId)&&idOf(activeCall.initiatedBy)===selfId,joinedHost=participantRole==="host"&&participantStatus==="joined",legacyRecoveredHost=!currentParticipant&&initiatedByCurrentUser&&activeCall.status==="active",canInvite=Boolean(repositoryId)&&activeCall.callType==="repository"&&activeCall.status==="active"&&activeCall.acceptingParticipants!==false&&(joinedHost||legacyRecoveredHost);
  const participantIds=useMemo(()=>new Set((activeCall.participants||[]).filter(row=>["invited","ringing","joined"].includes(row.status)).map(idOf)),[activeCall.participants]);
  const available=useMemo(()=>members.filter(member=>{const memberId=idOf(member),status=String(member.status||member.accessStatus||member.membershipStatus||"").toLowerCase(),expiry=member.temporaryAccessExpiresAt||member.expiresAt||member.accessExpiresAt,expired=Boolean(expiry&&new Date(expiry).getTime()<=Date.now());return memberId!==selfId&&!participantIds.has(memberId)&&!["joined","invited","ringing"].includes(String(member.invitationStatus||"").toLowerCase())&&!member.expired&&member.isActive!==false&&!new Set(["suspended","removed","declined","pending","inactive","expired","not_started"]).has(status)&&!expired;}),[members,participantIds,selfId]);
  const eligible=useMemo(()=>{const term=search.trim().toLowerCase();return available.filter(member=>!term||String(member.username||member.user?.username||"").toLowerCase().includes(term)||String(member.name||member.user?.name||"").toLowerCase().includes(term));},[available,search]);
  const occupied=(activeCall.participants||[]).filter(row=>["invited","ringing","joined"].includes(row.status)).length,remaining=Math.max(0,(activeCall.maxParticipants||4)-occupied);
  const show=()=>{const request=++requestRef.current;setOpen(true);setLoading(true);setMembers([]);setMessage(null);getRepositoryCallMembers(repositoryId,activeCall._id).then(data=>{if(request===requestRef.current)setMembers(data.members||[]);}).catch(()=>{if(request===requestRef.current)setMessage({type:"error",text:"The repository members could not be loaded. Try again."});}).finally(()=>{if(request===requestRef.current)setLoading(false);});};
  const close=()=>{requestRef.current+=1;setOpen(false);setSearch("");setSelected("");setMessage(null);};
  const submit=async event=>{event.preventDefault();if(!selected||sending)return;const member=members.find(value=>idOf(value)===selected);setSending(true);setMessage(null);try{await invite(selected);setMessage({type:"success",text:`Invitation sent to ${member?.username||member?.user?.username||"repository member"}.`});setMembers(values=>values.filter(value=>idOf(value)!==selected));setSelected("");}catch(error){setMessage({type:"error",text:invitationMessage(error)});}finally{setSending(false);}};
  if(!canInvite)return null;
  if(!open)return <button type="button" aria-label="Invite repository member" onClick={show} disabled={!remaining}>Invite participants</button>;
  return <form className="call-member-invite" onSubmit={submit}><div className="call-member-invite-heading"><strong>Invite participants</strong><button type="button" onClick={close}>Close</button></div><p>{remaining} of {(activeCall.maxParticipants||4)-1} invitation slots available</p><label>Search repository members<input autoComplete="off" placeholder="Search repository members" value={search} onChange={event=>{setSearch(event.target.value);setSelected("");setMessage(null);}}/></label>{loading?<p role="status">Loading repository members…</p>:available.length===0&&!message?<p>No eligible repository members.</p>:eligible.length===0&&!message?<p>No matching repository members.</p>:eligible.length>0?<ul className="call-member-results">{eligible.map(member=>{const user=member.user||member,memberId=idOf(member),expiry=member.temporaryAccessExpiresAt;return <li key={memberId}><button type="button" className={selected===memberId?"selected":""} onClick={()=>{setSelected(memberId);setMessage(null);}}>{user.avatarUrl?<img src={user.avatarUrl} alt=""/>:<span className="call-member-avatar" aria-hidden="true">{(user.name||user.username||"?").charAt(0).toUpperCase()}</span>}<span><strong>{user.username}</strong>{user.name&&<small>{user.name}</small>}<small>{member.online?"Online":"Offline"}{expiry?` · Access expires ${new Date(expiry).toLocaleString()}`:""}</small></span><span className={`collaborator-role collaborator-role--${member.role}`}>{roleLabel(member.role)}</span></button></li>;})}</ul>:null}<button type="submit" disabled={!selected||sending||loading||!remaining}>{sending?"Sending invitation…":"Invite"}</button>{message&&<p className={`call-invite-message call-invite-message--${message.type}`} role={message.type==="error"?"alert":"status"}>{message.text}</p>}</form>;
}
