// @vitest-environment jsdom
import React from"react";
import{cleanup,fireEvent,render,screen}from"@testing-library/react";
import{afterEach,beforeEach,describe,expect,test,vi}from"vitest";
import CallMemberInvite from"./CallMemberInvite";

const mocks=vi.hoisted(()=>({members:vi.fn()}));
vi.mock("../../authContext",()=>({useAuth:()=>({currentUser:{_id:"me"}})}));
vi.mock("../../services/callApi",()=>({getRepositoryCallMembers:mocks.members}));
const member=(id,username,role="reviewer",extra={})=>({user:{_id:id,username,name:`${username} name`,avatarUrl:`/${id}.png`},role,status:"active",...extra});
const activeCall={_id:"call1",callType:"repository",status:"active",repository:"repo1",maxParticipants:4,participants:[{user:{_id:"me"},status:"joined",role:"host"},{user:{_id:"joined"},status:"joined"},{user:{_id:"invited"},status:"invited"}]};
const values=[member("me","current"),member("joined","joined-user"),member("invited","invited-user"),member("reviewer","review-user"),member("viewer","spectator-user","viewer"),member("expired","expired-user","temporary_contributor",{accessExpiresAt:"2020-01-01T00:00:00Z"}),member("removed","removed-user","tester",{status:"suspended"})];
const open=async invite=>{render(<CallMemberInvite activeCall={activeCall} invite={invite}/>);expect(screen.queryByText("Invite user ID")).toBeNull();fireEvent.click(screen.getByRole("button",{name:"Invite repository member"}));await screen.findByText("review-user");};
beforeEach(()=>mocks.members.mockResolvedValue({members:values}));afterEach(()=>{cleanup();vi.clearAllMocks();});

describe("repository call member selector",()=>{
  test("search loads active members and marks joined and invited users",async()=>{await open(vi.fn());expect(mocks.members).toHaveBeenCalledWith("repo1","call1");expect(screen.getAllByText("Reviewer").length).toBeGreaterThan(0);expect(screen.getByText("Viewer")).toBeTruthy();expect(screen.getByRole("button",{name:/joined-user/i}).disabled).toBe(true);expect(screen.getByRole("button",{name:/invited-user/i}).disabled).toBe(true);for(const name of["current","expired-user","removed-user"])expect(screen.queryByText(name)).toBeNull();fireEvent.change(screen.getByPlaceholderText("Search repository members"),{target:{value:"spectator"}});expect(screen.getByText("spectator-user")).toBeTruthy();expect(screen.queryByText("review-user")).toBeNull();fireEvent.change(screen.getByPlaceholderText("Search repository members"),{target:{value:"missing"}});expect(screen.getByText("No matching repository members.")).toBeTruthy();});
  test("Invite stays disabled until an explicit member selection",async()=>{await open(vi.fn());expect(screen.getByRole("button",{name:"Invite"}).disabled).toBe(true);const card=screen.getByRole("button",{name:/review-user/i});fireEvent.click(card);expect(card.getAttribute("aria-pressed")).toBe("true");expect(card.classList.contains("call-invite-member--selected")).toBe(true);expect(screen.getByRole("button",{name:"Invite"}).disabled).toBe(false);});
  test("selecting ankit sends only ankit's normalized ID and name",async()=>{const invite=vi.fn().mockResolvedValue({invitee:{id:"ankit-id",username:"ankit"}});mocks.members.mockResolvedValue({members:[member("honey-id","honey"),member("ankit-id","ankit")]});const call={...activeCall,participants:[activeCall.participants[0]]};render(<CallMemberInvite activeCall={call} invite={invite}/>);fireEvent.click(screen.getByRole("button",{name:"Invite repository member"}));await screen.findByText("ankit");fireEvent.click(screen.getByRole("button",{name:/ankit/i}));fireEvent.click(screen.getByRole("button",{name:"Invite"}));expect(await screen.findByText("Invitation sent to ankit.")).toBeTruthy();expect(invite).toHaveBeenCalledOnce();expect(invite).toHaveBeenCalledWith("ankit-id");});
  test("selection sends the internal ID and reports success",async()=>{const invite=vi.fn().mockResolvedValue({});await open(invite);fireEvent.click(screen.getByRole("button",{name:/review-user/i}));fireEvent.click(screen.getByRole("button",{name:"Invite"}));await screen.findByText("Invitation sent to review-user.");expect(invite).toHaveBeenCalledWith("reviewer");});
  test("Invite is disabled while pending and repeated clicks are prevented",async()=>{let release;const invite=vi.fn(()=>new Promise(resolve=>{release=resolve;}));await open(invite);fireEvent.click(screen.getByRole("button",{name:/review-user/i}));const button=screen.getByRole("button",{name:"Invite"});fireEvent.click(button);expect((await screen.findByRole("button",{name:"Sending…"})).disabled).toBe(true);fireEvent.click(screen.getByRole("button",{name:"Sending…"}));expect(invite).toHaveBeenCalledTimes(1);release({});await screen.findByText("Invitation sent to review-user.");});
  test("permission errors stay inline and the selector remains usable",async()=>{const invite=vi.fn().mockRejectedValue(Object.assign(new Error("denied"),{code:"CALL_FORBIDDEN"}));await open(invite);fireEvent.click(screen.getByRole("button",{name:/review-user/i}));fireEvent.click(screen.getByRole("button",{name:"Invite"}));expect((await screen.findByRole("alert")).textContent).toContain("You do not have permission to invite participants.");expect(screen.getByPlaceholderText("Search repository members")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Close"}));expect(screen.queryByRole("alert")).toBeNull();});
  test("success uses the server-confirmed invitee name for the selected ID",async()=>{const invite=vi.fn().mockResolvedValue({inviteeDisplayName:"review-user"});await open(invite);fireEvent.click(screen.getByRole("button",{name:/review-user/i}));fireEvent.click(screen.getByRole("button",{name:"Invite"}));expect(await screen.findByText("Invitation sent to review-user.")).toBeTruthy();expect(invite).toHaveBeenCalledOnce();expect(invite).toHaveBeenCalledWith("reviewer");});
  test("rate limits show a retry countdown and never retry automatically",async()=>{const invite=vi.fn().mockRejectedValue(Object.assign(new Error("Please wait before sending another invitation."),{code:"CALL_INVITE_RATE_LIMITED",retryAfterSeconds:5}));await open(invite);fireEvent.click(screen.getByRole("button",{name:/review-user/i}));fireEvent.click(screen.getByRole("button",{name:"Invite"}));expect(await screen.findByRole("button",{name:"Try again in 5s"})).toBeTruthy();expect(screen.getByRole("alert").textContent).toContain("Please wait before sending another invitation.");expect(invite).toHaveBeenCalledOnce();});
  test("a full call disables invitation creation",()=>{const fullCall={...activeCall,participants:[...activeCall.participants,{user:{_id:"fourth"},status:"joined"}]};render(<CallMemberInvite activeCall={fullCall} invite={vi.fn()}/>);expect(screen.getByRole("button",{name:"Invite repository member"}).disabled).toBe(true);expect(screen.getByText("Call full")).toBeTruthy();});
  test("empty eligible and loading states render",async()=>{let resolve;mocks.members.mockReturnValue(new Promise(done=>{resolve=done;}));render(<CallMemberInvite activeCall={activeCall} invite={vi.fn()}/>);fireEvent.click(screen.getByRole("button",{name:"Invite repository member"}));expect(screen.getByText("Loading repository members…")).toBeTruthy();resolve({members:[member("me","current")]});expect(await screen.findByText("No eligible repository members.")).toBeTruthy();});
});
