import React,{useMemo,useRef,useState}from"react";
import{useAuth}from"../../authContext";
import{getRepositoryCallMembers}from"../../services/callApi";

const idOf=value=>String(value?.user?._id||value?.user?.id||value?.user||value?._id||value?.id||value||"");
const roleLabel=value=>String(value||"member").split("_").map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(" ");
const invitationMessage=error=>({CALL_MEMBER_NOT_FOUND:"Repository member not found.",CALL_MEMBER_INACTIVE:"This user no longer has active repository access.",CALL_MEMBER_ACCESS_EXPIRED:"This user's temporary repository access has expired.",CALL_ALREADY_PARTICIPANT:"This user is already in the call.",CALL_ALREADY_INVITED:"This user has already been invited.",CALL_PARTICIPANT_LIMIT:"This call has reached the four-participant limit.",CALL_FORBIDDEN:"You do not have permission to invite participants."}[error?.code]||"The invitation could not be sent. Try again.");

export default function CallMemberInvite({activeCall,invite}){
  const auth=useAuth(),selfId=String(auth?.currentUser?._id||auth?.currentUser?.id||""),repositoryId=idOf(activeCall.repository),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[members,setMembers]=useState([]),[loadedAt,setLoadedAt]=useState(0),[search,setSearch]=useState(""),[selected,setSelected]=useState(""),[sending,setSending]=useState(false),[message,setMessage]=useState(null),requestRef=useRef(0);
  const selfParticipant=(activeCall.participants||[]).find(row=>idOf(row)===selfId);
  const participantIds=useMemo(()=>new Set((activeCall.participants||[]).filter(row=>["invited","ringing","joined"].includes(row.status)).map(idOf)),[activeCall.participants]);
  const available=useMemo(()=>members.filter(member=>{const userId=idOf(member),temporary=member.role==="temporary_contributor",inactive=member.status!=="active"||(member.accessStartsAt&&new Date(member.accessStartsAt).getTime()>loadedAt)||(temporary&&member.accessExpiresAt&&new Date(member.accessExpiresAt).getTime()<=loadedAt);return!inactive&&userId!==selfId&&!participantIds.has(userId);}),[loadedAt,members,participantIds,selfId]);
  const eligible=useMemo(()=>{const term=search.trim().toLowerCase();return available.filter(member=>!term||String(member.user?.username||"").toLowerCase().includes(term)||String(member.user?.name||"").toLowerCase().includes(term));},[available,search]);
  const show=()=>{const request=++requestRef.current;setOpen(true);setLoading(true);setMembers([]);setLoadedAt(0);setMessage(null);getRepositoryCallMembers(repositoryId).then(data=>{if(request===requestRef.current){setMembers(data.members||data.collaborators||[]);setLoadedAt(Date.now());}}).catch(()=>{if(request===requestRef.current)setMessage({type:"error",text:"The repository members could not be loaded. Try again."});}).finally(()=>{if(request===requestRef.current)setLoading(false);});};
  const close=()=>{requestRef.current+=1;setOpen(false);setSearch("");setSelected("");setMessage(null);};
  const submit=async event=>{event.preventDefault();if(!selected||sending)return;const member=members.find(value=>idOf(value)===selected);setSending(true);setMessage(null);try{await invite(selected);setMessage({type:"success",text:`Invitation sent to ${member?.user?.username||"repository member"}.`});setSelected("");}catch(error){setMessage({type:"error",text:invitationMessage(error)});}finally{setSending(false);}};
  if(!repositoryId||selfParticipant?.role!=="host"||selfParticipant.status!=="joined")return null;
  if(!open)return <button type="button" onClick={show}>Invite repository member</button>;
  return <form className="call-member-invite" onSubmit={submit}><div className="call-member-invite-heading"><strong>Invite repository member</strong><button type="button" onClick={close}>Close</button></div><label>Search repository members<input autoComplete="off" placeholder="Search repository members" value={search} onChange={event=>{setSearch(event.target.value);setSelected("");setMessage(null);}}/></label>{loading?<p role="status">Loading repository members…</p>:available.length===0&&!message?<p>No eligible repository members.</p>:eligible.length===0&&!message?<p>No matching repository members.</p>:eligible.length>0?<ul className="call-member-results">{eligible.map(member=>{const user=member.user||{},memberId=idOf(member);return <li key={memberId}><button type="button" className={selected===memberId?"selected":""} onClick={()=>{setSelected(memberId);setMessage(null);}}>{user.avatarUrl?<img src={user.avatarUrl} alt=""/>:<span className="call-member-avatar" aria-hidden="true">{(user.name||user.username||"?").charAt(0).toUpperCase()}</span>}<span><strong>{user.username}</strong>{user.name&&<small>{user.name}</small>}</span><span className={`collaborator-role collaborator-role--${member.role}`}>{roleLabel(member.role)}</span></button></li>;})}</ul>:null}<button type="submit" disabled={!selected||sending||loading}>{sending?"Sending invitation…":"Invite"}</button>{message&&<p className={`call-invite-message call-invite-message--${message.type}`} role={message.type==="error"?"alert":"status"}>{message.text}</p>}</form>;
}
