import React,{useEffect,useMemo,useState}from"react";
import{useNavigate,useSearchParams}from"react-router-dom";
import Navbar from"../Navbar";
import{useChat}from"../../context/ChatContext";
import{useCall}from"../../context/CallContext";
import{mergeMessages}from"../../utils/chatMessages";
import{useAuth}from"../../authContext";
import{chatRequest}from"../../services/chatApi";
import MessageItem from"./MessageItem";
import MessageComposer from"./MessageComposer";
import{connectionLabel,getConversationHeaderMeta,normalizeId}from"./conversationHeader";
import"./chat.css";
import"./conversationLabels.css";

export default function ChatPage(){
  const chat=useChat(),call=useCall(),auth=useAuth(),navigate=useNavigate(),[params,setParams]=useSearchParams(),selected=params.get("conversation");
  const[reply,setReply]=useState(null),[search,setSearch]=useState(""),[results,setResults]=useState(null),[chatError,setChatError]=useState("");
  const currentUserId=auth.currentUser?._id||auth.currentUser?.id||auth.currentUser||localStorage.getItem("userId"),conversation=chat.conversations.find(value=>String(value._id)===selected),rows=chat.messages[selected]||[],other=conversation?.participants?.find(user=>normalizeId(user)!==normalizeId(currentUserId)),meta=getConversationHeaderMeta(conversation,{conversationPresence:chat.conversationPresence,userPresence:chat.presence,currentUserId});
  useEffect(()=>{chat.loadConversations();},[chat.loadConversations]);
  useEffect(()=>{setChatError("");call?.clearError?.();if(selected)chat.open(selected).catch(value=>setChatError(value.message));},[selected,chat.open,call?.clearError]);
  useEffect(()=>{if(!selected||!other?._id||conversation?.type!=="direct"||!chat.socket)return undefined;chat.socket.emit("presence:subscribe",{conversationId:selected,userId:other._id});return()=>chat.socket.emit("presence:unsubscribe",{userId:other._id});},[selected,other?._id,conversation?.type,chat.socket]);
  const send=async payload=>{const pending={_id:`pending:${payload.clientMessageId}`,conversation:selected,sender:{_id:currentUserId,username:"You"},sequence:Number.MAX_SAFE_INTEGER,createdAt:new Date().toISOString(),...payload,pending:true};chat.setMessages(current=>({...current,[selected]:mergeMessages(current[selected]||[],pending)}));try{const saved=await chat.send(selected,payload);chat.setMessages(current=>({...current,[selected]:mergeMessages(current[selected]||[],saved)}));}catch(value){chat.setMessages(current=>({...current,[selected]:(current[selected]||[]).map(item=>item._id===pending._id?{...item,pending:false,failed:true}:item)}));throw value;}};
  const update=message=>chat.setMessages(current=>({...current,[selected]:(current[selected]||[]).map(value=>String(value._id)===String(message._id)?message:value)}));
  const voiceSent=message=>chat.setMessages(current=>({...current,[selected]:[...(current[selected]||[]).filter(value=>String(value._id)!==String(message._id)),message].sort((a,b)=>a.sequence-b.sequence)}));
  const doSearch=async event=>{event.preventDefault();if(search.trim().length<2)return;const data=await chatRequest(`/chat/conversations/${selected}/search?q=${encodeURIComponent(search)}`);setResults(data.messages||[]);};
  const toggleMute=async()=>{await chatRequest(`/chat/conversations/${selected}/mute`,conversation.muted?{method:"DELETE"}:{method:"PATCH",body:JSON.stringify({duration:"indefinite"})});await chat.loadConversations();};
  const startContext=mediaMode=>call.start({callType:conversation.type,conversationId:selected,repositoryId:conversation.repository?._id||conversation.repository,issueId:conversation.issue?._id||conversation.issue,pullRequestId:conversation.pullRequest?._id||conversation.pullRequest,mediaMode}).catch(()=>{});
  const grouped=useMemo(()=>chat.conversations.reduce((map,value)=>{(map[value.type]||=[]).push(value);return map;},{}),[chat.conversations]);
  const messageRole=message=>conversation?.participants?.find(user=>normalizeId(user)===normalizeId(message.sender))?.role||null;
  const sidebarLabel=value=>{const valueMeta=getConversationHeaderMeta(value,{conversationPresence:chat.conversationPresence,userPresence:chat.presence,currentUserId});return value.type==="repository"?<span className="chat-conversation-label"><strong>{value.repository?.name||"Repository"}</strong><span>{valueMeta.title}</span></span>:<span>{valueMeta.title}</span>;};
  return <div className="chat-page"><Navbar/><main className={`chat-shell${selected?" chat-shell--open":""}`}>
    <aside className="chat-sidebar"><header><h1>CodeHub Chat</h1><span className={`chat-connection chat-connection--${chat.connection}`}>{connectionLabel(chat.connection)}</span></header><input aria-label="Search conversations" placeholder="Search conversations"/>{Object.entries(grouped).map(([type,items])=><section key={type}><h2>{type.replace("_"," ")}</h2>{items.map(value=><button className={String(value._id)===selected?"active":""} key={value._id} onClick={()=>setParams({conversation:value._id})}>{sidebarLabel(value)}{value.muted&&<span aria-label="Muted">Muted</span>}{value.unreadCount>0&&<strong aria-label={`${value.unreadCount} unread`}>{value.unreadCount}</strong>}</button>)}</section>)}</aside>
    <section className="chat-main">{selected&&conversation?<><header className="chat-header"><button className="chat-back" onClick={()=>navigate("/chat")}>Back</button><div><h2>{meta.title}</h2><p>{meta.subtitle}</p></div>{call&&conversation.type==="direct"&&other&&<><button type="button" disabled={call.checking} onClick={()=>call.start({recipientId:other._id,conversationId:selected,mediaMode:"audio"}).catch(()=>{})}>Audio call</button><button type="button" disabled={call.checking} onClick={()=>call.start({recipientId:other._id,conversationId:selected,mediaMode:"video"}).catch(()=>{})}>Video call</button></>}{call&&["repository","issue","pull_request","mentor"].includes(conversation.type)&&<button type="button" disabled={call.checking} onClick={()=>startContext("audio")}>{call.checking?"Checking call…":"Start context call"}</button>}<button type="button" onClick={toggleMute}>{conversation.muted?"Unmute":"Mute"}</button>{conversation.type==="direct"&&other&&<button type="button" onClick={async()=>{if(window.confirm(`Block ${other.username}?`)){await chatRequest(`/chat/users/${other._id}/block`,{method:"POST"});navigate("/chat");}}}>Block</button>}<form onSubmit={doSearch}><input aria-label="Search messages" value={search} onChange={event=>{setSearch(event.target.value);if(!event.target.value)setResults(null);}}/><button>Search</button></form></header>
      {(chatError||chat.accessError)&&<p className="chat-error" role="alert">{chatError||chat.accessError}</p>}<div className="chat-messages" aria-live="polite">{!results&&rows.length>=50&&<button className="chat-load-older" onClick={()=>chat.loadOlder(selected)}>Load older messages</button>}{(results||rows).map(message=><MessageItem key={message._id} message={message} senderRole={messageRole(message)} currentUserId={currentUserId} onReply={setReply} onChanged={update}/>)}{!rows.length&&!results&&<p className="chat-empty">No messages yet. Start the conversation.</p>}</div>
      {chat.typing[selected]&&<p className="chat-typing" aria-live="polite">{chat.typing[selected].username} is typing…</p>}<MessageComposer conversationId={selected} onVoiceSent={voiceSent} reply={reply} onCancelReply={()=>setReply(null)} onSend={send} onTyping={()=>chat.socket?.emit("typing:start",{conversationId:selected})} onStopTyping={()=>chat.socket?.emit("typing:stop",{conversationId:selected})} disabled={chat.connection!=="connected"}/></>:<div className="chat-welcome"><h2>Select a conversation</h2><p>Direct messages and repository conversations stay private to their permitted participants.</p></div>}</section>
  </main></div>;
}
