import React,{useRef,useState}from"react";
import{uploadChatAttachment}from"../../services/chatApi";
import VoiceRecorder from"./VoiceRecorder";

export default function MessageComposer({onSend,onVoiceSent,conversationId,reply,onCancelReply=()=>{},disabled,onTyping,onStopTyping}){
 const[content,setContent]=useState(""),[mode,setMode]=useState("text"),[file,setFile]=useState(null),[sending,setSending]=useState(false),[error,setError]=useState("");
 const clientId=useRef(null),attachmentId=useRef(null),typingTimer=useRef(null),textareaRef=useRef(null);
 const changed=event=>{setContent(event.target.value);if(error){clientId.current=null;attachmentId.current=null;setError("");}onTyping?.();clearTimeout(typingTimer.current);typingTimer.current=setTimeout(()=>onStopTyping?.(),1200);};
 const submit=async event=>{event?.preventDefault();if(!content.trim()&&!file)return;setSending(true);setError("");onStopTyping?.();try{if(file&&!attachmentId.current)attachmentId.current=(await uploadChatAttachment(file)).attachment._id;clientId.current||=crypto.randomUUID();await onSend({clientMessageId:clientId.current,messageType:mode,content,codeLanguage:mode==="code"?"text":"",replyTo:reply?._id||null,attachmentIds:attachmentId.current?[attachmentId.current]:[]});setContent("");setFile(null);setMode("text");clientId.current=null;attachmentId.current=null;onCancelReply();}catch(value){setError(value.message);}finally{setSending(false);}};
 const keyDown=event=>{if(event.key==="Escape"){onCancelReply();setMode("text");}if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();submit();}};
 return <form className="chat-composer" onSubmit={submit}>{reply&&<div className="chat-composer-reply">Replying to {reply.sender?.username}<button id="cancel-reply" name="cancel-reply" type="button" onClick={onCancelReply}>Cancel</button></div>}{file&&<div className="chat-file-preview">{file.name}<button id="remove-attachment" name="remove-attachment" type="button" onClick={()=>{setFile(null);attachmentId.current=null;}}>Remove</button></div>}<textarea ref={textareaRef} id="chat-message" name="message" aria-label={mode==="code"?"Code snippet":"Message"} placeholder={mode==="code"?"Paste a code snippet":"Write a message"} value={content} onChange={changed} onKeyDown={keyDown} maxLength={mode==="code"?20000:10000}/><div><VoiceRecorder conversationId={conversationId} onSent={onVoiceSent} disabled={disabled}/><button id="message-code" name="message-code" type="button" aria-pressed={mode==="code"} onClick={()=>setMode(mode==="code"?"text":"code")}>Code</button><label className="chat-attach" htmlFor="chat-attachment">Attach<input id="chat-attachment" name="attachment" aria-label="Attach" type="file" onChange={event=>{setFile(event.target.files?.[0]||null);attachmentId.current=null;}}/></label><button id="send-message" name="send-message" type="submit" disabled={disabled||sending||(!content.trim()&&!file)}>{sending?"Sending…":"Send"}</button></div>{error&&<p role="alert">{error} <button id="retry-message" name="retry-message" type="button" onClick={submit}>Retry</button></p>}</form>;
}
