import React, { useCallback, useEffect, useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import Navbar from "../Navbar";
import MarkdownPreview from "../repository/MarkdownPreview";
import { downloadReleaseFile, formatBytes, releaseRequest } from "./releaseApi";
import "./releases.css";

const ReleaseDetailPage = () => {
  const { id, releaseId } = useParams(); const navigate = useNavigate(); const fileRef = useRef(null);
  const [state, setState] = useState({ loading: true, busy: false, error: "", release: null, canManage: false, editing: false });
  const [edit, setEdit] = useState({ title: "", body: "", prerelease: false, preview: false });
  const load = useCallback(async (signal) => { try { const data = await releaseRequest(`/repo/${id}/releases/${releaseId}`, { signal }); setState((current) => ({ ...current, loading: false, error: "", release: data.release, canManage: Boolean(data.canManage) })); setEdit({ title: data.release.title, body: data.release.body || "", prerelease: Boolean(data.release.prerelease), preview: false }); } catch (error) { if (error.name !== "AbortError") setState((current) => ({ ...current, loading: false, error: error.message })); } }, [id, releaseId]);
  useEffect(() => { const controller = new AbortController(); load(controller.signal); return () => controller.abort(); }, [load]);
  const run = async (operation) => { setState((current) => ({ ...current, busy: true, error: "" })); try { await operation(); await load(); setState((current) => ({ ...current, busy: false })); } catch (error) { setState((current) => ({ ...current, busy: false, error: error.message })); } };
  const save = () => run(async () => { await releaseRequest(`/repo/${id}/releases/${releaseId}`, { method: "PATCH", body: JSON.stringify({ title: edit.title, body: edit.body, prerelease: edit.prerelease }) }); setState((current) => ({ ...current, editing: false })); });
  const publish = () => run(() => releaseRequest(`/repo/${id}/releases/${releaseId}/publish`, { method: "POST" }));
  const remove = async () => { if (!window.confirm("Delete this release and all uploaded assets? The tag will remain.")) return; setState((current) => ({ ...current, busy: true })); try { await releaseRequest(`/repo/${id}/releases/${releaseId}`, { method: "DELETE" }); navigate(`/repo/${id}/releases`); } catch (error) { setState((current) => ({ ...current, busy: false, error: error.message })); } };
  const upload = (file) => { if (!file) return; run(async () => { const body = new FormData(); body.append("asset", file); await releaseRequest(`/repo/${id}/releases/${releaseId}/assets`, { method: "POST", body }); if (fileRef.current) fileRef.current.value = ""; }); };
  const deleteAsset = (asset) => { if (window.confirm(`Delete ${asset.name}?`)) run(() => releaseRequest(`/repo/${id}/releases/${releaseId}/assets/${asset._id}`, { method: "DELETE" })); };
  const download = async (path, name) => { try { await downloadReleaseFile(path, name); } catch (error) { setState((current) => ({ ...current, error: error.message })); } };
  if (state.loading) return <div className="releases-page"><Navbar /><main className="releases-container"><div className="release-state">Loading release...</div></main></div>;
  if (!state.release) return <div className="releases-page"><Navbar /><main className="releases-container"><div className="release-state release-state--error">{state.error || "Release not found"}</div></main></div>;
  const release = state.release;
  return <div className="releases-page"><Navbar /><main className="releases-container"><p><Link to={`/repo/${id}/releases`}>← Releases</Link></p>{state.error && <div className="release-state release-state--error" role="alert">{state.error}</div>}
    <header className="release-detail-header"><div><div className="release-badges">{release.latest && <span className="release-badge release-badge--latest">Latest</span>}{release.draft && <span className="release-badge">Draft</span>}{release.prerelease && <span className="release-badge release-badge--pre">Pre-release</span>}</div><h1>{release.title}</h1><p><strong>{release.tag?.name}</strong> · {release.publishedAt ? `published ${new Date(release.publishedAt).toLocaleString()}` : `draft created ${new Date(release.createdAt).toLocaleString()}`} by {release.createdBy?.username || "Deleted user"}</p></div>{state.canManage && <div className="release-detail-actions"><button className="release-secondary" onClick={() => setState((current) => ({ ...current, editing: !current.editing }))}>Edit</button>{release.draft && <button className="release-primary" disabled={state.busy} onClick={publish}>Publish</button>}<button className="release-danger" disabled={state.busy} onClick={remove}>Delete</button></div>}</header>
    {state.editing ? <section className="release-form release-edit"><label>Title<input value={edit.title} onChange={(event) => setEdit((current) => ({ ...current, title: event.target.value }))} /></label><label>Release notes <span className="release-label-action"><button onClick={() => setEdit((current) => ({ ...current, preview: !current.preview }))}>{edit.preview ? "Edit" : "Preview"}</button></span>{edit.preview ? <div className="release-preview"><MarkdownPreview content={edit.body || "Nothing to preview."} /></div> : <textarea rows="12" value={edit.body} onChange={(event) => setEdit((current) => ({ ...current, body: event.target.value }))} />}</label><label className="release-checkbox"><input type="checkbox" checked={edit.prerelease} onChange={(event) => setEdit((current) => ({ ...current, prerelease: event.target.checked }))} /> Pre-release</label><div className="release-form-actions"><button className="release-secondary" onClick={() => setState((current) => ({ ...current, editing: false }))}>Cancel</button><button className="release-primary" disabled={state.busy} onClick={save}>Save changes</button></div></section> : <section className="release-notes"><MarkdownPreview content={release.body || "No release notes were provided."} /></section>}
    <section className="release-downloads"><header><h2>Assets <span>{(release.assets?.length || 0) + 1}</span></h2>{state.canManage && <label className="release-secondary">Upload asset<input ref={fileRef} hidden type="file" onChange={(event) => upload(event.target.files?.[0])} /></label>}</header><ul><li><button onClick={() => download(`/repo/${id}/releases/${releaseId}/source.zip`, `${release.tag?.name || "source"}.zip`)}><span>Source code (zip)</span><small>Snapshot at {String(release.tag?.targetCommitHash || "").slice(0, 12)}</small></button></li>{(release.assets || []).map((asset) => <li key={asset._id}><button onClick={() => download(`/repo/${id}/releases/${releaseId}/assets/${asset._id}/download`, asset.name)}><span>{asset.name}</span><small>{formatBytes(asset.size)} · {asset.downloadCount || 0} downloads</small></button>{state.canManage && <button className="release-asset-delete" aria-label={`Delete ${asset.name}`} onClick={() => deleteAsset(asset)}>×</button>}</li>)}</ul></section>
  </main></div>;
};
export default ReleaseDetailPage;
