import React, { useState } from "react";
const labels={excellent:"Excellent",good:"Good",needs_improvement:"Needs improvement",poor:"Poor",critical:"Critical",insufficient_data:"Insufficient data"};
const HealthScoreCard=({data})=>{const[expanded,setExpanded]=useState(null);if(!data)return null;return <section className={`health-card health-card--${data.status}`} aria-labelledby="health-score-title">
 <div className="health-summary"><div className="health-gauge" role="img" aria-label={`Project health score ${data.score} out of 100`} style={{"--health-score":data.score}}><strong>{data.score}</strong><span>/ 100</span></div><div><p className="health-kicker">Project health</p><h2 id="health-score-title">{labels[data.status]||data.status}</h2><p>{data.insufficientData?"There is not enough project activity for a reliable classification yet.":`Calculated from stored evidence over ${data.range}.`}</p></div></div>
 <div className="health-categories">{Object.entries(data.categories||{}).map(([key,item])=><article key={key}><button type="button" aria-expanded={expanded===key} onClick={()=>setExpanded(expanded===key?null:key)}><span>{item.label}</span><strong>{item.score}/{item.max}</strong></button><progress value={item.score} max={item.max} aria-label={`${item.label} ${item.score} out of ${item.max}`}/>{expanded===key&&<ul>{item.details.map(row=><li key={row.label}><div><strong>{row.label}</strong><span className={`health-check health-check--${row.status}`}>{row.status==="not_configured"?"Not configured":row.status}</span></div><p>{row.evidence}</p>{row.recommendation&&<p className="health-recommendation">{row.recommendation}</p>}</li>)}</ul>}</article>)}</div>
 {data.recommendations?.length>0&&<div className="health-next"><h3>Recommended next steps</h3><ol>{data.recommendations.map(item=><li key={item}>{item}</li>)}</ol></div>}
 {data.trend&&<p className="health-trend">Change since the previous snapshot: <strong>{data.trend.change>0?"+":""}{data.trend.change}</strong></p>}
 <p className="health-meta">Last calculated {new Date(data.calculatedAt).toLocaleString()} · Version {data.version} · {data.range}</p>
 <details className="health-explanation"><summary>How this score is calculated</summary><p>Version {data.version}: Documentation 15, Automated Tests 20, Maintenance 10, Issue Management 10, Security 15, Code Quality 15, Build and Deployment 5, and Beginner Friendliness 10. Only stored repository evidence earns points; CodeHub never runs repository commands to calculate health.</p></details>
</section>};
export default HealthScoreCard;
