// @vitest-environment jsdom
import React from "react";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes, useLocation } from "react-router-dom";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import ContributionHome from "./ContributionHome";
import SkillProfileForm from "./SkillProfileForm";
import RecommendationCard from "./RecommendationCard";
import RepositoryContribute from "./RepositoryContribute";
import ContributionSession from "./ContributionSession";
import { contributionRequest } from "../../services/contributionApi";

const contributionCss = readFileSync(resolve("src/components/contributions/contributions.css"), "utf8").replace(/\s+/g, "");

vi.mock("../Navbar", () => ({ default: () => <nav aria-label="CodeHub navigation">Navigation</nav> }));
vi.mock("../../services/contributionApi", () => ({ contributionRequest: vi.fn() }));

const profile = { experienceLevel: "beginner", skills: ["React", "JavaScript", "CSS"], preferredTaskTypes: ["UI improvement"], availableTime: "30_to_60_minutes", learningGoals: [], visibility: "private", updatedAt: "today" };
const repository = { _id: "r1", name: "interface", visibility: "private", owner: { username: "ada" }, issues: [{ status: "open", contributionGuide: { enabled: true } }] };
const item = { issueId: "i1", issueNumber: 7, title: "Improve mobile layout", repository: { _id: "r1", name: "interface" }, suitabilityScore: 92, suitabilityLabel: "Excellent match", difficulty: "beginner", estimatedMinutes: 45, taskType: "UI improvement", requiredSkills: ["React", "CSS"], matchedSkills: ["React", "CSS"], reasons: ["Matches React and CSS", "Fits your selected availability"], missingSkills: ["Accessibility"], warnings: ["You may need help with Accessibility"], labels: [{ name: "good first issue" }], breakdown: { requiredSkills: 35, experience: 20, time: 15, taskType: 10, clarity: 7, eligibility: 5, beginnerFriendly: 0 }, actionable: true };
const sessionData = { session: { _id: "s1", status: "branch_created", branchName: "mentor/ada/issue-7-improve-mobile-layout", branchApprovalRequired: false, finalReport: null, recommendationSnapshot: { suitabilityScore: 92, missingSkills: ["Accessibility"] }, skillProfileSnapshot: profile }, issue: { number: 7, title: "Improve mobile layout", contributionGuide: { difficulty: "beginner", estimatedMinutes: 45, requiredSkills: ["React", "CSS"], completionChecks: [] } }, repository: { _id: "r1", name: "interface" }, progress: { percent: 35, items: [{ key: "branch", label: "Personal branch created", status: "completed", evidenceType: "branch" }] }, validation: { changedFiles: [{ path: "src/App.jsx", status: "modified" }], checks: [{ key: "stored", status: "warning", message: "No testing evidence is available.", checkType: "test_result_available" }] }, relevantFiles: [{ path: "src/App.jsx", purpose: "Contains a user-interface component.", relevance: "required", exists: true }], canManage: false };
const Location = () => <output>{useLocation().pathname}</output>;
const fillRequiredProfile = () => { fireEvent.change(screen.getByLabelText("Experience level"), { target: { value: "beginner" } }); fireEvent.click(screen.getByLabelText("React")); fireEvent.click(screen.getByLabelText("UI improvement")); fireEvent.change(screen.getByLabelText("Available time"), { target: { value: "30_to_60_minutes" } }); };
const mockHome = ({ repositories = [repository], recommendations = [item], sessions = [], putError = null } = {}) => contributionRequest.mockImplementation((path, options = {}) => {
  if (path === "/contributions/profile" && options.method === "PUT") return putError ? Promise.reject(new Error(putError)) : Promise.resolve({ profile, message: "saved" });
  if (path === "/contributions/profile") return Promise.resolve({ profile: null });
  if (path === "/contributions/history") return Promise.resolve({ sessions: [], skillProgress: [] });
  if (path === "/repo/all") return Promise.resolve(repositories);
  if (path.includes("contribution-recommendations")) return Promise.resolve({ recommendations, profile });
  if (path.endsWith("contribution-sessions") && options.method === "POST") return Promise.resolve({ session: { _id: "s-new" } });
  if (path.endsWith("contribution-sessions")) return Promise.resolve({ sessions });
  return Promise.reject(new Error(`Unexpected request ${path}`));
});

describe("Guided Contribution frontend", () => {
  beforeEach(() => vi.clearAllMocks());
  afterEach(cleanup);

  it("renders the responsive hero heading without inline CSS", async () => { mockHome(); const { container } = render(<MemoryRouter><ContributionHome /></MemoryRouter>); const title = await screen.findByRole("heading", { level: 1, name: /Build contribution skills with real repository work/ }); expect(title.className).toContain("contribution-hero-title"); expect(title.getAttribute("style")).toBeNull(); expect(container.querySelector(".contribution-hero-description")).toBeTruthy(); });
  it("defines balanced responsive hero rules at tablet, mobile, and small-mobile widths", () => { expect(contributionCss).toContain("line-height:1.07"); expect(contributionCss).toContain("@media(max-width:767px)"); expect(contributionCss).toContain("@media(max-width:419px)"); expect(contributionCss).toContain("overflow-x:clip"); expect(contributionCss).not.toContain("position:absolute"); });
  it("uses theme tokens for dark, light, and system-resolved themes", () => { expect(contributionCss).toContain("var(--bg-page)"); expect(contributionCss).toContain("var(--bg-surface)"); expect(contributionCss).toContain("var(--text-primary)"); expect(contributionCss).toContain("var(--accent-link)"); });
  it("renders experience, skill groups, preferred tasks, and available time", () => { render(<SkillProfileForm onSave={vi.fn()} />); expect(screen.getByLabelText("Experience level")).toBeTruthy(); for (const group of ["Frontend", "Backend", "Testing", "Development"]) expect(screen.getByText(group, { selector: "legend" })).toBeTruthy(); expect(screen.getByText("Preferred tasks", { selector: "legend" })).toBeTruthy(); expect(screen.getByLabelText("Available time")).toBeTruthy(); });
  it("shows inline skill, task, experience, and time validation", () => { render(<SkillProfileForm onSave={vi.fn()} />); fireEvent.click(screen.getByRole("button", { name: "Find suitable issues" })); expect(screen.getByText("Select at least one skill.")).toBeTruthy(); expect(screen.getByText("Select at least one preferred task.")).toBeTruthy(); expect(screen.getByText("Select your available time.")).toBeTruthy(); expect(screen.getByText("Select your experience level.")).toBeTruthy(); });
  it("preserves selections after validation failure", () => { render(<SkillProfileForm onSave={vi.fn()} />); fireEvent.click(screen.getByLabelText("React")); fireEvent.click(screen.getByRole("button", { name: "Find suitable issues" })); expect(screen.getByLabelText("React").checked).toBe(true); });
  it("submits a complete profile", async () => { const save = vi.fn(async () => {}); render(<SkillProfileForm onSave={save} />); fillRequiredProfile(); fireEvent.click(screen.getByRole("button", { name: "Find suitable issues" })); await waitFor(() => expect(save).toHaveBeenCalledWith(expect.objectContaining({ skills: ["React"], preferredTaskTypes: ["UI improvement"] }))); });
  it("shows a loading label and disables profile submission", () => { render(<SkillProfileForm initial={profile} onSave={vi.fn()} busy />); const button = screen.getByRole("button", { name: "Finding suitable issues…" }); expect(button.disabled).toBe(true); expect(button.getAttribute("aria-busy")).toBe("true"); });
  it("prevents duplicate profile submission", async () => { let resolve; const save = vi.fn(() => new Promise(done => { resolve = done; })); render(<SkillProfileForm onSave={save} />); fillRequiredProfile(); const button = screen.getByRole("button", { name: "Find suitable issues" }); fireEvent.click(button); fireEvent.click(button); expect(save).toHaveBeenCalledTimes(1); resolve(); });
  it("shows only authorized repository selector entries", async () => { mockHome({ repositories: [repository, { _id: "hidden", name: "secret", visibility: "private", accessible: false }] }); render(<MemoryRouter><ContributionHome /></MemoryRouter>); const selector = await screen.findByLabelText("Repository"); expect(selector.textContent).toContain("ada / interface"); expect(selector.textContent).not.toContain("secret"); });
  it("keeps repository selection optional until finding issues", async () => { mockHome(); render(<MemoryRouter><ContributionHome /></MemoryRouter>); await screen.findByLabelText("Repository"); expect(screen.getByText("Select a repository to find guided issues.")).toBeTruthy(); });
  it("saves a profile then loads recommendations", async () => { mockHome(); render(<MemoryRouter><ContributionHome /></MemoryRouter>); fireEvent.change(await screen.findByLabelText("Repository"), { target: { value: "r1" } }); fillRequiredProfile(); fireEvent.click(screen.getByRole("button", { name: "Find suitable issues" })); expect(await screen.findByText("Improve mobile layout")).toBeTruthy(); expect(contributionRequest).toHaveBeenCalledWith("/contributions/profile", expect.objectContaining({ method: "PUT" })); });
  it("preserves the form and displays Retry after a profile API error", async () => { mockHome({ putError: "Network unavailable" }); render(<MemoryRouter><ContributionHome /></MemoryRouter>); fireEvent.change(await screen.findByLabelText("Repository"), { target: { value: "r1" } }); fillRequiredProfile(); fireEvent.click(screen.getByRole("button", { name: "Find suitable issues" })); expect(await screen.findByText("Network unavailable")).toBeTruthy(); expect(screen.getByRole("button", { name: "Retry" })).toBeTruthy(); expect(screen.getByLabelText("React").checked).toBe(true); });
  it("renders score, repository, reasons, required, matched, missing skills, warnings, and labels", () => { render(<MemoryRouter><RecommendationCard item={item} repositoryId="r1" onStart={vi.fn()} /></MemoryRouter>); expect(screen.getByLabelText("Suitability score 92 percent")).toBeTruthy(); expect(screen.getByText("interface")).toBeTruthy(); expect(screen.getByText("Matches React and CSS")).toBeTruthy(); expect(screen.getByText("Required skills")).toBeTruthy(); expect(screen.getByText("Matched skills")).toBeTruthy(); expect(screen.getByText("Learning skills")).toBeTruthy(); expect(screen.getByText("good first issue")).toBeTruthy(); });
  it("shows the exact no-guided-issues state", async () => { contributionRequest.mockImplementation(path => Promise.resolve(path.includes("recommendations") ? { recommendations: [], profile } : { sessions: [] })); render(<MemoryRouter initialEntries={["/repo/r1/contribute"]}><Routes><Route path="/repo/:id/contribute" element={<RepositoryContribute />} /></Routes></MemoryRouter>); expect(await screen.findByText("No guided issues are configured in this repository yet.")).toBeTruthy(); });
  it("shows the no-strong-match state and all-issues action", async () => { contributionRequest.mockImplementation(path => Promise.resolve(path.includes("recommendations") ? { recommendations: [{ ...item, suitabilityScore: 40 }], profile } : { sessions: [] })); render(<MemoryRouter initialEntries={["/repo/r1/contribute"]}><Routes><Route path="/repo/:id/contribute" element={<RepositoryContribute />} /></Routes></MemoryRouter>); expect(await screen.findByText("No strong matches were found for your current profile.")).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: "Show all guided issues" })); expect(screen.getByText("Improve mobile layout")).toBeTruthy(); });
  it("starts a contribution and navigates to its session", async () => { mockHome(); render(<MemoryRouter><Routes><Route path="*" element={<><ContributionHome /><Location /></>} /></Routes></MemoryRouter>); fireEvent.change(await screen.findByLabelText("Repository"), { target: { value: "r1" } }); fillRequiredProfile(); fireEvent.click(screen.getByRole("button", { name: "Find suitable issues" })); fireEvent.click(await screen.findByRole("button", { name: "Start guided contribution" })); await waitFor(() => expect(screen.getByText("/repo/r1/contribute/session/s-new")).toBeTruthy()); });
  it("renders Continue session for an existing active session", () => { const existing = { _id: "s1" }; const start = vi.fn(); render(<MemoryRouter><RecommendationCard item={item} repositoryId="r1" activeSession={existing} onStart={start} /></MemoryRouter>); fireEvent.click(screen.getByRole("button", { name: "Continue session" })); expect(start).toHaveBeenCalledWith(item, existing); });
  it("shows recommendation skeletons while loading", () => { contributionRequest.mockReturnValue(new Promise(() => {})); const { container } = render(<MemoryRouter initialEntries={["/repo/r1/contribute"]}><Routes><Route path="/repo/:id/contribute" element={<RepositoryContribute />} /></Routes></MemoryRouter>); expect(container.querySelectorAll(".recommendation-skeleton").length).toBe(2); });
  it("keeps the existing navbar usable", async () => { mockHome(); render(<MemoryRouter><ContributionHome /></MemoryRouter>); expect(await screen.findByRole("navigation", { name: "CodeHub navigation" })).toBeTruthy(); });
  it("renders session repository, score, difficulty, estimate, branch, progress, files, guidance, mentor, and skills", async () => { contributionRequest.mockResolvedValue(sessionData); render(<MemoryRouter initialEntries={["/repo/r1/contribute/session/s1"]}><Routes><Route path="/repo/:id/contribute/session/:sessionId" element={<ContributionSession />} /></Routes></MemoryRouter>); expect(await screen.findByText("35%")).toBeTruthy(); expect(screen.getByText(/interface · Issue #7/)).toBeTruthy(); expect(screen.getByText("92%")).toBeTruthy(); expect(screen.getByText("45 minutes")).toBeTruthy(); expect(screen.getAllByText("mentor/ada/issue-7-improve-mobile-layout").length).toBeGreaterThan(0); expect(screen.getAllByText("src/App.jsx").length).toBeGreaterThan(0); expect(screen.getByText("Commit and pull-request guidance")).toBeTruthy(); expect(screen.getByRole("button", { name: "Request mentor help" })).toBeTruthy(); expect(screen.getByText("Skills being practised")).toBeTruthy(); });
  it("requires an explicit commit message", async () => { contributionRequest.mockResolvedValue(sessionData); render(<MemoryRouter initialEntries={["/repo/r1/contribute/session/s1"]}><Routes><Route path="/repo/:id/contribute/session/:sessionId" element={<ContributionSession />} /></Routes></MemoryRouter>); await screen.findByText("35%"); expect(screen.getByRole("button", { name: "Confirm and create local commit" }).disabled).toBe(true); });
  it("renders branch approval and evidence-based final report states", async () => { contributionRequest.mockResolvedValue({ ...sessionData, session: { ...sessionData.session, branchApprovalRequired: true, finalReport: { score: 85, skillsDemonstrated: [{ skill: "React", evidence: [{ type: "file_change" }] }] } } }); render(<MemoryRouter initialEntries={["/repo/r1/contribute/session/s1"]}><Routes><Route path="/repo/:id/contribute/session/:sessionId" element={<ContributionSession />} /></Routes></MemoryRouter>); expect(await screen.findByText("Branch approval required")).toBeTruthy(); expect(screen.getByText("85/100")).toBeTruthy(); expect(screen.getByText(/React — supported by file_change/)).toBeTruthy(); });
});
