import React, { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import Navbar from "../Navbar";
import { contributionRequest } from "../../services/contributionApi";
import "./contributions.css";

const ContributionSession = () => {
  const { id, sessionId } = useParams(); const [state, setState] = useState({ loading: true, data: null, error: "", message: "", busy: "" }); const [commitMessage, setCommitMessage] = useState(""); const [pr, setPr] = useState({ title: "", description: "" });
  const load = useCallback(() => contributionRequest(`/repo/${id}/contribution-sessions/${sessionId}`).then(data => { setState(current => ({ ...current, loading: false, data, error: "" })); setCommitMessage(current => current || data.guidance?.suggestedCommitMessage || ""); setPr(current => ({ title: current.title || data.guidance?.suggestedPullRequestTitle || data.issue.title, description: current.description || data.guidance?.suggestedPullRequestDescription || `Guided contribution for issue #${data.issue.number}` })); }).catch(error => setState(current => ({ ...current, loading: false, error: error.message }))), [id, sessionId]);
  useEffect(() => { load(); }, [load]);
  const action = async (name, path = name, body = {}) => { setState(current => ({ ...current, busy: name, error: "", message: "" })); try { const data = await contributionRequest(`/repo/${id}/contribution-sessions/${sessionId}/${path}`, { method: "POST", body }); setState(current => ({ ...current, busy: "", message: data.message || "Session updated" })); await load(); } catch (error) { setState(current => ({ ...current, busy: "", error: error.message })); } };
  const patch = async (actionName, body = {}) => { setState(current => ({ ...current, busy: actionName, error: "" })); try { const data = await contributionRequest(`/repo/${id}/contribution-sessions/${sessionId}`, { method: "PATCH", body: { action: actionName, ...body } }); setState(current => ({ ...current, busy: "", message: data.message })); await load(); } catch (error) { setState(current => ({ ...current, busy: "", error: error.message })); } };
  if (state.loading) return <div className="contribution-page"><Navbar /><main className="contribution-container" role="status">Loading contribution session…</main></div>;
  if (!state.data) return <div className="contribution-page"><Navbar /><main className="contribution-container contribution-alert" role="alert">{state.error}</main></div>;
  const { session, issue, progress, validation, relevantFiles, canManage } = state.data;
  return <div className="contribution-page"><Navbar /><main className="contribution-container"><header className="contribution-heading"><div><p><Link to={`/repo/${id}/contribute`}>← Contributions</Link></p><h1>{issue.title}</h1><p>Issue #{issue.number} · {session.status.replaceAll("_", " ")}</p></div><div className="session-progress"><strong>{progress.percent}%</strong><span>complete</span></div></header>{state.error && <div className="contribution-alert" role="alert">{state.error}</div>}{state.message && <div className="contribution-success" role="status">{state.message}</div>}
    {session.branchApprovalRequired && <section className="contribution-panel contribution-panel--warning"><h2>Branch approval required</h2><p>Your temporary repository access does not yet include <code>{session.branchName}</code>.</p>{canManage ? <button className="contribution-primary" onClick={() => patch("approve_branch")}>Approve branch access</button> : <p>A maintainer has been notified. You can continue after approval.</p>}</section>}
    <section className="contribution-panel"><div className="contribution-section-title"><h2>Guided workflow</h2><button className="contribution-secondary" disabled={!!state.busy} onClick={() => action("validate")}>Refresh evidence</button></div><ol className="progress-checklist">{progress.items.map(item => <li className={`progress-checklist__${item.status}`} key={item.key}><span aria-hidden="true">{item.status === "completed" ? "✓" : "○"}</span><div><strong>{item.label}</strong><small>{item.evidenceType.replaceAll("_", " ")}</small></div></li>)}</ol></section>
    <div className="contribution-two-column"><section className="contribution-panel"><h2>Relevant files</h2>{!relevantFiles.length ? <p>No safe file hints are configured.</p> : <ul className="file-hints">{relevantFiles.map(file => <li key={file.path}><code>{file.path}</code><p>{file.purpose}</p><span>{file.relevance}{file.exists === false ? " · not currently present" : ""}</span></li>)}</ul>}</section><section className="contribution-panel"><h2>Validation evidence</h2><p>CodeHub inspects stored metadata only. It never runs repository code during this validation.</p><ul className="validation-list">{validation.checks.map(check => <li key={check.key} className={`validation-${check.status}`}><strong>{check.status}</strong><span>{check.message}</span>{check.checkType === "user_confirmation" && check.status !== "passed" && <button onClick={() => action(`confirm-${check.key}`, "confirm-check", { key: check.key, confirmed: true })}>Confirm</button>}{check.checkType === "maintainer_confirmation" && check.status !== "passed" && canManage && <button onClick={() => patch("confirm_check", { key: check.key })}>Maintainer confirms</button>}</li>)}</ul></section></div>
    <section className="contribution-panel"><h2>Next actions</h2><div className="workflow-actions"><button className="contribution-primary" disabled={!!state.busy || !!session.branchName && !session.branchApprovalRequired} onClick={() => action("branch")}>{session.branchName ? "Branch requested" : "Create personal branch"}</button>{session.branchName && <code>{session.branchName}</code>}</div><div className="workflow-form"><label>Commit message<input value={commitMessage} onChange={event => setCommitMessage(event.target.value)} placeholder="Describe the completed change" /></label><button className="contribution-secondary" disabled={!!state.busy || !session.branchName || !commitMessage.trim()} onClick={() => action("commit", "commit", { message: commitMessage, confirmed: true })}>Confirm and create local commit</button><p>Stage files with the existing file workflow first. After committing, push the branch with the existing repository Push action.</p></div><div className="workflow-form"><label>Pull request title<input value={pr.title} onChange={event => setPr({ ...pr, title: event.target.value })} /></label><label>Description<textarea rows="4" value={pr.description} onChange={event => setPr({ ...pr, description: event.target.value })} /></label><button className="contribution-primary" disabled={!!state.busy || !session.branchName} onClick={() => action("pull-request", "pull-request", { ...pr, confirmed: true })}>Confirm and open pull request</button></div><div className="workflow-actions"><button className="contribution-secondary" onClick={() => action("mentor", "mentor-request", { message: "Could you help me with this guided contribution?" })}>Request mentor</button><button className="contribution-primary" onClick={() => action("complete")}>Complete from evidence</button><button className="contribution-danger" onClick={() => patch("abandon")}>Abandon session</button></div></section>
    {session.finalReport && <section className="contribution-panel contribution-report"><h2>Contribution report</h2><strong className="report-score">{session.finalReport.score}/100</strong><h3>Skills demonstrated</h3><ul>{session.finalReport.skillsDemonstrated.map(item => <li key={item.skill}>{item.skill} — supported by {item.evidence.map(value => value.type).join(", ")}</li>)}</ul><p>This report reflects stored evidence only; it does not infer unobserved skill.</p></section>}
  </main></div>;
};
export default ContributionSession;
