// @vitest-environment jsdom
import React from "react";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import SkillProfileForm from "./SkillProfileForm";
import RepositoryContribute, { RecommendationCard } from "./RepositoryContribute";
import ContributionSession from "./ContributionSession";
import { contributionRequest } from "../../services/contributionApi";

vi.mock("../Navbar", () => ({ default: () => <nav>Navigation</nav> }));
vi.mock("../../services/contributionApi", () => ({ contributionRequest: vi.fn() }));

const item = { issueId: "i1", issueNumber: 7, title: "Improve layout", suitabilityScore: 92, suitabilityLabel: "Excellent match", difficulty: "beginner", estimatedMinutes: 60, reasons: ["Matches React", "Fits your selected availability"], missingSkills: ["Accessibility"], breakdown: { requiredSkills: 35, experience: 20, time: 15, taskType: 10, clarity: 7, eligibility: 5, beginnerFriendly: 0 }, actionable: true };
const sessionData = { session: { _id: "s1", status: "branch_created", branchName: "contribute/ada/issue-7-abcde", branchApprovalRequired: false, finalReport: null }, issue: { number: 7, title: "Improve layout", contributionGuide: { completionChecks: [] } }, progress: { percent: 35, items: [{ key: "branch", label: "Personal branch created", status: "completed", evidenceType: "branch" }] }, validation: { checks: [{ key: "stored", status: "warning", message: "No testing evidence is available.", checkType: "test_result_available" }] }, relevantFiles: [{ path: "src/App.jsx", purpose: "Contains a user-interface component.", relevance: "required", exists: true }], canManage: false };

describe("Guided Contribution UI", () => {
  beforeEach(() => vi.clearAllMocks());
  afterEach(cleanup);
  it("renders the skill profile form", () => { render(<SkillProfileForm onSave={vi.fn()} />); expect(screen.getByText("Experience level")).toBeTruthy(); expect(screen.getByText("Skills")).toBeTruthy(); });
  it("changes experience and availability", () => { render(<SkillProfileForm onSave={vi.fn()} />); fireEvent.change(screen.getByLabelText("Experience level"), { target: { value: "advanced" } }); fireEvent.change(screen.getByLabelText("Available time"), { target: { value: "more_than_4_hours" } }); expect(screen.getByLabelText("Experience level").value).toBe("advanced"); });
  it("selects skills and task types", () => { render(<SkillProfileForm onSave={vi.fn()} />); fireEvent.click(screen.getByLabelText("React")); fireEvent.click(screen.getByLabelText("Bug fixing")); expect(screen.getByLabelText("React").checked).toBe(true); expect(screen.getByLabelText("Bug fixing").checked).toBe(true); });
  it("requires a skill before profile submission", () => { render(<SkillProfileForm onSave={vi.fn()} />); expect(screen.getByRole("button", { name: "Save contribution profile" }).disabled).toBe(true); });
  it("submits normalized profile input", () => { const save = vi.fn(); render(<SkillProfileForm onSave={save} />); fireEvent.click(screen.getByLabelText("React")); fireEvent.click(screen.getByRole("button", { name: "Save contribution profile" })); expect(save).toHaveBeenCalledWith(expect.objectContaining({ skills: ["React"] })); });
  it("renders recommendation score, reasons, and missing skills", () => { render(<MemoryRouter><RecommendationCard item={item} repositoryId="r1" onStart={vi.fn()} /></MemoryRouter>); expect(screen.getByLabelText("Suitability score 92 out of 100")).toBeTruthy(); expect(screen.getByText(/Matches React/)).toBeTruthy(); expect(screen.getByText(/Accessibility/)).toBeTruthy(); });
  it("starts a recommended contribution explicitly", () => { const start = vi.fn(); render(<MemoryRouter><RecommendationCard item={item} repositoryId="r1" onStart={start} /></MemoryRouter>); fireEvent.click(screen.getByRole("button", { name: "Start guided contribution" })); expect(start).toHaveBeenCalledWith(item); });
  it("shows an empty recommendation state", async () => { contributionRequest.mockImplementation(path => Promise.resolve(path.includes("recommendations") ? { recommendations: [] } : { sessions: [] })); render(<MemoryRouter initialEntries={["/repo/r1/contribute"]}><Routes><Route path="/repo/:id/contribute" element={<RepositoryContribute />} /></Routes></MemoryRouter>); expect(await screen.findByText("No guided issues yet")).toBeTruthy(); });
  it("shows recommendation API errors", async () => { contributionRequest.mockRejectedValue(new Error("Profile required")); render(<MemoryRouter initialEntries={["/repo/r1/contribute"]}><Routes><Route path="/repo/:id/contribute" element={<RepositoryContribute />} /></Routes></MemoryRouter>); expect((await screen.findByRole("alert")).textContent).toContain("Profile required"); });
  it("renders session progress, relevant files, validation, and commit guide", async () => { contributionRequest.mockResolvedValue(sessionData); render(<MemoryRouter initialEntries={["/repo/r1/contribute/session/s1"]}><Routes><Route path="/repo/:id/contribute/session/:sessionId" element={<ContributionSession />} /></Routes></MemoryRouter>); expect(await screen.findByText("35%")).toBeTruthy(); expect(screen.getByText("src/App.jsx")).toBeTruthy(); expect(screen.getByText("No testing evidence is available.")).toBeTruthy(); expect(screen.getByLabelText("Commit message")).toBeTruthy(); });
  it("requires a commit message before explicit commit", async () => { contributionRequest.mockResolvedValue(sessionData); render(<MemoryRouter initialEntries={["/repo/r1/contribute/session/s1"]}><Routes><Route path="/repo/:id/contribute/session/:sessionId" element={<ContributionSession />} /></Routes></MemoryRouter>); await screen.findByText("35%"); expect(screen.getByRole("button", { name: "Confirm and create local commit" }).disabled).toBe(true); });
  it("renders branch approval state", async () => { contributionRequest.mockResolvedValue({ ...sessionData, session: { ...sessionData.session, branchApprovalRequired: true }, canManage: false }); render(<MemoryRouter initialEntries={["/repo/r1/contribute/session/s1"]}><Routes><Route path="/repo/:id/contribute/session/:sessionId" element={<ContributionSession />} /></Routes></MemoryRouter>); expect(await screen.findByText("Branch approval required")).toBeTruthy(); });
  it("renders evidence-based final report", async () => { contributionRequest.mockResolvedValue({ ...sessionData, session: { ...sessionData.session, finalReport: { score: 85, skillsDemonstrated: [{ skill: "React", evidence: [{ type: "file_change" }] }] } } }); render(<MemoryRouter initialEntries={["/repo/r1/contribute/session/s1"]}><Routes><Route path="/repo/:id/contribute/session/:sessionId" element={<ContributionSession />} /></Routes></MemoryRouter>); expect(await screen.findByText("85/100")).toBeTruthy(); expect(screen.getByText(/React — supported by file_change/)).toBeTruthy(); });
});
