import React, { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import Navbar from "../Navbar";
import { contributionRequest } from "../../services/contributionApi";
import "./contributions.css";

const Score = ({ value }) => <div className="contribution-score" aria-label={`Suitability score ${value} out of 100`}><strong>{value}</strong><span>/100</span></div>;
export const RecommendationCard = ({ item, repositoryId, onStart, busy }) => <article className="recommendation-card"><div className="recommendation-card__top"><div><p className="contribution-kicker">Issue #{item.issueNumber}</p><h2>{item.title}</h2></div><Score value={item.suitabilityScore} /></div><div className="contribution-tags"><span>{item.suitabilityLabel}</span><span>{item.difficulty}</span><span>{item.estimatedMinutes} min estimate</span></div><p>{item.reasons.join(" · ") || "No strong match signals were found."}</p>{item.missingSkills.length > 0 && <p className="contribution-warning">Skills to learn: {item.missingSkills.join(", ")}</p>}<details><summary>Why this score?</summary><dl className="score-breakdown">{Object.entries(item.breakdown).map(([key, value]) => <div key={key}><dt>{key.replace(/([A-Z])/g, " $1")}</dt><dd>{value}</dd></div>)}</dl></details><div className="recommendation-actions"><Link to={`/repo/${repositoryId}/issues/${item.issueNumber}`}>View issue</Link><button className="contribution-primary" disabled={busy || !item.actionable} onClick={() => onStart(item)}>{item.actionable ? "Start guided contribution" : "Repository access required"}</button></div></article>;

const RepositoryContribute = () => {
  const { id } = useParams(); const [state, setState] = useState({ loading: true, recommendations: [], sessions: [], error: "", busy: "" });
  const load = useCallback(() => Promise.all([contributionRequest(`/repo/${id}/contribution-recommendations`), contributionRequest(`/repo/${id}/contribution-sessions`)]).then(([matches, sessions]) => setState(current => ({ ...current, loading: false, recommendations: matches.recommendations || [], sessions: sessions.sessions || [], error: "" }))).catch(error => setState(current => ({ ...current, loading: false, error: error.message }))), [id]);
  useEffect(() => { load(); }, [load]);
  const start = async item => { setState(current => ({ ...current, busy: item.issueId, error: "" })); try { const data = await contributionRequest(`/repo/${id}/contribution-sessions`, { method: "POST", body: { issueId: item.issueId } }); window.location.assign(`/repo/${id}/contribute/session/${data.session._id}`); } catch (error) { setState(current => ({ ...current, busy: "", error: error.message })); } };
  return <div className="contribution-page"><Navbar /><main className="contribution-container"><header className="contribution-heading"><div><p><Link to={`/repo/${id}`}>← Repository</Link></p><h1>Contribute</h1><p>Recommendations use only your saved profile and maintainer-authored issue guidance.</p></div><Link className="contribution-secondary" to="/profile/contributions">Profile and history</Link></header>{state.loading && <p role="status">Ranking guided issues…</p>}{state.error && <div className="contribution-alert" role="alert"><p>{state.error}</p>{state.error.toLowerCase().includes("profile") && <p><Link to="/contribute">Create profile</Link></p>}<button className="contribution-secondary" onClick={load}>Retry</button></div>}
    {!!state.sessions.length && <section className="contribution-panel"><h2>Your sessions</h2><div className="contribution-list">{state.sessions.map(session => <article key={session._id}><div><strong>{session.issue?.title}</strong><p>{session.status.replaceAll("_", " ")} · {session.latestProgressPercent}%</p></div><Link to={`/repo/${id}/contribute/session/${session._id}`}>Open</Link></article>)}</div></section>}
    {!state.loading && !state.error && <section aria-label="Recommended contributions"><div className="contribution-section-title"><h2>Recommended issues</h2><span>{state.recommendations.length} available</span></div>{!state.recommendations.length ? <div className="contribution-empty"><h3>No guided issues yet</h3><p>Maintainers can add a contribution guide from any issue page.</p></div> : <div className="recommendation-grid">{state.recommendations.map(item => <RecommendationCard key={item.issueId} item={item} repositoryId={id} onStart={start} busy={state.busy === item.issueId} />)}</div>}</section>}
  </main></div>;
};
export default RepositoryContribute;
