import React,{createContext,useCallback,useContext,useEffect,useMemo,useRef,useState}from"react";
import{useChat}from"./ChatContext";
import{getIceServers}from"../services/callApi";
import{useAuth}from"../authContext";

const Context=createContext(null),emit=(socket,event,payload)=>new Promise((resolve,reject)=>{if(!socket?.connected)return reject(new Error("Calling is offline"));socket.emit(event,payload,result=>result?.success?resolve(result.call||result.data?.call||result):reject(Object.assign(new Error(result?.message||"Call request failed"),{code:result?.error})));});
const mediaError=error=>error?.name==="NotAllowedError"?"Media permission was denied.":error?.name==="NotFoundError"?"The requested microphone or camera is unavailable.":error?.message||"Unable to access media devices.";
const userId=value=>String(value?.user?._id||value?.user||value?._id||value||"");

export const CallProvider=({children})=>{
  const{socket}=useChat(),auth=useAuth(),selfId=String(auth?.currentUser?._id||auth?.currentUser?.id||localStorage.getItem("userId")||""),[incoming,setIncoming]=useState(null),[call,setCall]=useState(null),[localStream,setLocalStream]=useState(null),[remoteStreams,setRemoteStreams]=useState({}),[error,setError]=useState(""),[quality,setQuality]=useState("good"),[devices,setDevices]=useState([]),[elapsed,setElapsed]=useState(0),[reconnecting,setReconnecting]=useState(false);
  const peers=useRef(new Map()),callRef=useRef(null),streamRef=useRef(null),iceRef=useRef([]),screenRef=useRef(null);
  useEffect(()=>{callRef.current=call;},[call]);useEffect(()=>{streamRef.current=localStream;},[localStream]);
  const cleanup=useCallback(()=>{for(const peer of peers.current.values())peer.close();peers.current.clear();for(const track of streamRef.current?.getTracks?.()||[])track.stop();for(const track of screenRef.current?.getTracks?.()||[])track.stop();screenRef.current=null;setLocalStream(null);setRemoteStreams({});setCall(null);setIncoming(null);setElapsed(0);setReconnecting(false);},[]);
  const loadDevices=useCallback(async()=>{if(!navigator.mediaDevices?.enumerateDevices)return[];const rows=await navigator.mediaDevices.enumerateDevices();setDevices(rows);return rows;},[]);
  const acquire=useCallback(async(video=false,constraints={})=>{if(!navigator.mediaDevices?.getUserMedia)throw new Error("WebRTC media is not supported by this browser.");const stream=await navigator.mediaDevices.getUserMedia({audio:constraints.audio||true,video:video?(constraints.video||true):false});setLocalStream(stream);await loadDevices();return stream;},[loadDevices]);
  const ensureIce=useCallback(async()=>{if(iceRef.current.length)return iceRef.current;try{iceRef.current=(await getIceServers()).iceServers||[];}catch{iceRef.current=[{urls:"stun:stun.l.google.com:19302"}];}return iceRef.current;},[]);
  const peerFor=useCallback(async(target)=>{const key=String(target);if(peers.current.has(key))return peers.current.get(key);if(!window.RTCPeerConnection)throw new Error("WebRTC is not supported by this browser.");const peer=new RTCPeerConnection({iceServers:await ensureIce()});for(const track of streamRef.current?.getTracks?.()||[])peer.addTrack(track,streamRef.current);peer.ontrack=event=>setRemoteStreams(current=>({...current,[key]:event.streams[0]||new MediaStream([event.track])}));peer.onicecandidate=event=>event.candidate&&socket.emit("webrtc:ice-candidate",{callId:callRef.current?._id,to:key,candidate:event.candidate.toJSON?.()||event.candidate},()=>{});peer.onconnectionstatechange=()=>{const state=peer.connectionState;setQuality(state==="connected"?"good":state==="connecting"?"fair":state==="disconnected"?"reconnecting":state==="failed"?"poor":"good");setReconnecting(state==="disconnected"||state==="connecting");};peers.current.set(key,peer);return peer;},[ensureIce,socket]);
  const offerTo=useCallback(async target=>{const peer=await peerFor(target),description=await peer.createOffer();await peer.setLocalDescription(description);await emit(socket,"webrtc:offer",{callId:callRef.current._id,to:target,description:peer.localDescription});},[peerFor,socket]);
  const start=useCallback(async({recipientId,conversationId,mediaMode="audio",...context})=>{setError("");try{await acquire(mediaMode==="video");const value=await emit(socket,"call:initiate",{recipientId,conversationId,mediaMode,...context});setCall(value);return value;}catch(value){for(const track of streamRef.current?.getTracks?.()||[])track.stop();setLocalStream(null);setError(mediaError(value));throw value;}},[acquire,socket]);
  const accept=useCallback(async(camera=true)=>{setError("");try{await acquire(incoming?.mediaMode==="video"&&camera);const value=await emit(socket,incoming?.invitation?"call:join":"call:accept",{callId:incoming._id,cameraEnabled:camera});setCall(value);setIncoming(null);return value;}catch(value){setError(mediaError(value));throw value;}},[acquire,incoming,socket]);
  const reject=useCallback(async()=>{if(incoming)await emit(socket,incoming.invitation?"call:leave":"call:reject",{callId:incoming._id});setIncoming(null);},[incoming,socket]);
  const end=useCallback(async()=>{try{if(callRef.current)await emit(socket,callRef.current.status==="ringing"?"call:cancel":"call:end",{callId:callRef.current._id});}finally{cleanup();}},[cleanup,socket]);
  const toggleMicrophone=useCallback(async()=>{const track=streamRef.current?.getAudioTracks?.()[0];if(!track)return;track.enabled=!track.enabled;await emit(socket,"media:microphone",{callId:callRef.current._id,enabled:track.enabled});setCall(current=>({...current,localMicrophoneEnabled:track.enabled}));},[socket]);
  const toggleCamera=useCallback(async()=>{let track=streamRef.current?.getVideoTracks?.()[0];if(!track){const extra=await navigator.mediaDevices.getUserMedia({video:true});track=extra.getVideoTracks()[0];streamRef.current.addTrack(track);for(const peer of peers.current.values())peer.addTrack(track,streamRef.current);setLocalStream(streamRef.current);}else track.enabled=!track.enabled;await emit(socket,"media:camera",{callId:callRef.current._id,enabled:track.enabled});setCall(current=>({...current,localCameraEnabled:track.enabled}));},[socket]);
  const shareScreen=useCallback(async()=>{if(!navigator.mediaDevices?.getDisplayMedia)throw new Error("Screen sharing is not supported by this browser.");const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false}),track=stream.getVideoTracks()[0];await emit(socket,"media:screen-start",{callId:callRef.current._id});screenRef.current=stream;for(const peer of peers.current.values()){const sender=peer.getSenders().find(value=>value.track?.kind==="video");if(sender)await sender.replaceTrack(track);else peer.addTrack(track,stream);}track.onended=()=>stopScreen().catch(()=>{});setCall(current=>({...current,screenSharing:true}));},[socket]);
  const stopScreen=useCallback(async()=>{if(!callRef.current)return;const camera=streamRef.current?.getVideoTracks?.()[0]||null;for(const peer of peers.current.values()){const sender=peer.getSenders().find(value=>value.track?.kind==="video");if(sender)await sender.replaceTrack(camera);}for(const track of screenRef.current?.getTracks?.()||[])track.stop();screenRef.current=null;await emit(socket,"media:screen-stop",{callId:callRef.current._id});setCall(current=>({...current,screenSharing:false}));},[socket]);
  const toggleHand=useCallback(async()=>{const raised=!callRef.current?.localHandRaised;await emit(socket,raised?"call:hand-raise":"call:hand-lower",{callId:callRef.current._id});setCall(current=>({...current,localHandRaised:raised}));},[socket]);
  const invite=useCallback(user=>emit(socket,"call:invite",{callId:callRef.current._id,userId:user}),[socket]);
  const selectDevice=useCallback(async(kind,deviceId)=>{if(kind==="audiooutput")return;const stream=await navigator.mediaDevices.getUserMedia({[kind==="audioinput"?"audio":"video"]:{deviceId:{exact:deviceId}}}),track=stream.getTracks()[0],old=kind==="audioinput"?streamRef.current.getAudioTracks()[0]:streamRef.current.getVideoTracks()[0];old?.stop();if(old)streamRef.current.removeTrack(old);streamRef.current.addTrack(track);for(const peer of peers.current.values()){const sender=peer.getSenders().find(value=>value.track?.kind===track.kind);if(sender)await sender.replaceTrack(track);}setLocalStream(streamRef.current);},[]);

  useEffect(()=>{if(!socket)return undefined;const onIncoming=value=>setIncoming(value),onAccepted=async value=>{setCall(value);setIncoming(null);if(userId(value.initiatedBy)===selfId)for(const participant of value.participants||[])if(userId(participant)!==selfId&&participant.status==="joined")await offerTo(userId(participant)).catch(value=>setError(value.message));},onEnded=()=>cleanup(),onJoined=async value=>{setCall(current=>value.call||current);if(value.userId&&String(value.userId)!==selfId)await offerTo(value.userId).catch(()=>{});},onOffer=async value=>{const peer=await peerFor(value.from);await peer.setRemoteDescription(value.description);const answer=await peer.createAnswer();await peer.setLocalDescription(answer);await emit(socket,"webrtc:answer",{callId:value.callId,to:value.from,description:peer.localDescription});},onAnswer=async value=>(await peerFor(value.from)).setRemoteDescription(value.description),onIce=async value=>{if(value.candidate)await(await peerFor(value.from)).addIceCandidate(value.candidate);},onRevoked=()=>{setError("Your access to this call was revoked.");cleanup();};socket.on("call:incoming",onIncoming);socket.on("call:accepted",onAccepted);socket.on("call:ended",onEnded);socket.on("call:cancelled",onEnded);socket.on("call:rejected",onEnded);socket.on("call:missed",onEnded);socket.on("call:participant-joined",onJoined);socket.on("webrtc:offer",onOffer);socket.on("webrtc:answer",onAnswer);socket.on("webrtc:ice-candidate",onIce);socket.on("call:access-revoked",onRevoked);return()=>{for(const[event,fn]of [["call:incoming",onIncoming],["call:accepted",onAccepted],["call:ended",onEnded],["call:cancelled",onEnded],["call:rejected",onEnded],["call:missed",onEnded],["call:participant-joined",onJoined],["webrtc:offer",onOffer],["webrtc:answer",onAnswer],["webrtc:ice-candidate",onIce],["call:access-revoked",onRevoked]])socket.off(event,fn);};},[cleanup,offerTo,peerFor,selfId,socket]);
  useEffect(()=>{if(!socket)return undefined;const invited=value=>setIncoming(value);socket.on("call:invite-received",invited);return()=>socket.off("call:invite-received",invited);},[socket]);
  useEffect(()=>{if(!call?.answeredAt)return undefined;const started=new Date(call.answeredAt).getTime(),timer=setInterval(()=>setElapsed(Math.max(0,Math.floor((Date.now()-started)/1000))),1000);return()=>clearInterval(timer);},[call?.answeredAt]);
  useEffect(()=>{if(!socket)return undefined;const reconnect=()=>{if(callRef.current){setReconnecting(true);emit(socket,"call:rejoin",{callId:callRef.current._id}).then(value=>{setCall(value);setReconnecting(false);}).catch(()=>{setError("The call could not be recovered safely.");cleanup();});}};socket.on("connect",reconnect);return()=>socket.off("connect",reconnect);},[cleanup,socket]);
  const value=useMemo(()=>({incoming,call,localStream,remoteStreams,error,quality,devices,elapsed,reconnecting,start,accept,reject,end,toggleMicrophone,toggleCamera,shareScreen,stopScreen,toggleHand,invite,selectDevice,loadDevices}),[incoming,call,localStream,remoteStreams,error,quality,devices,elapsed,reconnecting,start,accept,reject,end,toggleMicrophone,toggleCamera,shareScreen,stopScreen,toggleHand,invite,selectDevice,loadDevices]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
};
export const useCall=()=>useContext(Context);
