import React,{createContext,useCallback,useContext,useEffect,useMemo,useRef,useState}from"react";
import{useChat}from"./ChatContext";
import{getActiveCall,getIceServers}from"../services/callApi";
import{useAuth}from"../authContext";

const Context=createContext(null),emit=(socket,event,payload)=>new Promise((resolve,reject)=>{if(!socket?.connected)return reject(new Error("Calling is offline"));socket.emit(event,payload,result=>result?.success?resolve(result.call||result.data?.call||result):reject(Object.assign(new Error(result?.message||"Call request failed"),{code:result?.error})));});
const mediaError=error=>error?.name==="NotAllowedError"?"Media permission was denied.":error?.name==="NotFoundError"?"The requested microphone or camera is unavailable.":error?.message||"Unable to access media devices.";
const userId=value=>String(value?.user?._id||value?.user||value?._id||value||"");

export const CallProvider=({children})=>{
  const{socket}=useChat(),auth=useAuth(),selfId=String(auth?.currentUser?._id||auth?.currentUser?.id||localStorage.getItem("userId")||""),[incoming,setIncoming]=useState(null),[call,setCall]=useState(null),[recovery,setRecovery]=useState(null),[checking,setChecking]=useState(false),[localStream,setLocalStream]=useState(null),[remoteStreams,setRemoteStreams]=useState({}),[error,setError]=useState(""),[quality,setQuality]=useState("good"),[devices,setDevices]=useState([]),[elapsed,setElapsed]=useState(0),[reconnecting,setReconnecting]=useState(false);
  const peers=useRef(new Map()),pendingIceCandidatesRef=useRef(new Map()),callRef=useRef(null),streamRef=useRef(null),iceRef=useRef([]),screenRef=useRef(null),startingRef=useRef(false);
  useEffect(()=>{callRef.current=call;},[call]);useEffect(()=>{streamRef.current=localStream;},[localStream]);
  const signalKey=useCallback((callId,target)=>`${String(callId||"")}:${String(target||"")}`,[ ]);
  const queueIceCandidate=useCallback((callId,target,candidate)=>{const key=signalKey(callId,target),queued=pendingIceCandidatesRef.current.get(key)||[];queued.push(candidate);pendingIceCandidatesRef.current.set(key,queued);},[signalKey]);
  const flushIceCandidates=useCallback(async(callId,target,peer)=>{if(!peer?.remoteDescription||peer.signalingState==="closed")return;const key=signalKey(callId,target),queued=pendingIceCandidatesRef.current.get(key)||[];pendingIceCandidatesRef.current.delete(key);for(const candidate of queued){try{if(peer.signalingState!=="closed")await peer.addIceCandidate(candidate);}catch(error){setError(error?.message||"Unable to add ICE candidate.");}}},[signalKey]);
  const cleanup=useCallback(()=>{for(const peer of peers.current.values())peer.close();peers.current.clear();pendingIceCandidatesRef.current.clear();for(const track of streamRef.current?.getTracks?.()||[])track.stop();for(const track of screenRef.current?.getTracks?.()||[])track.stop();screenRef.current=null;setLocalStream(null);setRemoteStreams({});setCall(null);setIncoming(null);setRecovery(null);setElapsed(0);setReconnecting(false);},[]);
  const restore=useCallback(value=>{if(!value){setIncoming(null);return setRecovery(null);}const participant=(value.participants||[]).find(row=>userId(row)===selfId);const pendingInvitation=participant?.status==="invited";const incomingCall=(value.status==="ringing"&&participant?.status==="ringing")||(value.status==="active"&&pendingInvitation);if(incomingCall&&userId(value.initiatedBy)!==selfId){setIncoming(value);setRecovery(null);}else setRecovery(value);},[selfId]);
  const refreshActive=useCallback(async()=>{if(!selfId)return null;setChecking(true);try{const value=(await getActiveCall()).call||null;restore(value);return value;}finally{setChecking(false);}},[restore,selfId]);
  const loadDevices=useCallback(async()=>{if(!navigator.mediaDevices?.enumerateDevices)return[];const rows=await navigator.mediaDevices.enumerateDevices();setDevices(rows);return rows;},[]);
  const acquire=useCallback(async(video=false,constraints={})=>{if(!navigator.mediaDevices?.getUserMedia)throw new Error("WebRTC media is not supported by this browser.");const stream=await navigator.mediaDevices.getUserMedia({audio:constraints.audio||true,video:video?(constraints.video||true):false});setLocalStream(stream);await loadDevices();return stream;},[loadDevices]);
  const ensureIce=useCallback(async()=>{if(iceRef.current.length)return iceRef.current;try{iceRef.current=(await getIceServers()).iceServers||[];}catch{iceRef.current=[{urls:"stun:stun.l.google.com:19302"}];}return iceRef.current;},[]);
  const peerFor=useCallback(async(target)=>{const key=String(target);if(peers.current.has(key))return peers.current.get(key);if(!window.RTCPeerConnection)throw new Error("WebRTC is not supported by this browser.");const peer=new RTCPeerConnection({iceServers:await ensureIce()}),peerCallId=callRef.current?._id,nativeSetRemoteDescription=peer.setRemoteDescription.bind(peer),nativeAddIceCandidate=peer.addIceCandidate.bind(peer);peer.setRemoteDescription=async description=>{const result=await nativeSetRemoteDescription(description);await flushIceCandidates(peerCallId,key,peer);return result;};peer.addIceCandidate=async candidate=>{if(peer.signalingState==="closed")return;if(!peer.remoteDescription){queueIceCandidate(peerCallId,key,candidate);return;}return nativeAddIceCandidate(candidate);};for(const track of streamRef.current?.getTracks?.()||[])peer.addTrack(track,streamRef.current);peer.ontrack=event=>setRemoteStreams(current=>({...current,[key]:event.streams[0]||new MediaStream([event.track])}));peer.onicecandidate=event=>event.candidate&&socket.emit("webrtc:ice-candidate",{callId:callRef.current?._id,to:key,candidate:event.candidate.toJSON?.()||event.candidate},()=>{});peer.onconnectionstatechange=()=>{const state=peer.connectionState;setQuality(state==="connected"?"good":state==="connecting"?"fair":state==="disconnected"?"reconnecting":state==="failed"?"poor":"good");setReconnecting(state==="disconnected"||state==="connecting");};peers.current.set(key,peer);return peer;},[ensureIce,flushIceCandidates,queueIceCandidate,socket]);
  const offerTo=useCallback(async target=>{const peer=await peerFor(target),description=await peer.createOffer();await peer.setLocalDescription(description);await emit(socket,"webrtc:offer",{callId:callRef.current._id,to:target,description:peer.localDescription});},[peerFor,socket]);
  const start=useCallback(async({recipientId,conversationId,mediaMode="audio",...context})=>{if(startingRef.current)return null;startingRef.current=true;setChecking(true);setError("");try{const existing=(await getActiveCall()).call||null;if(existing){restore(existing);return null;}await acquire(mediaMode==="video");const value=await emit(socket,"call:initiate",{recipientId,conversationId,mediaMode,...context});setRecovery(null);setCall(value);return value;}catch(value){for(const track of streamRef.current?.getTracks?.()||[])track.stop();setLocalStream(null);if(value.code==="CALL_ALREADY_ACTIVE"){const existing=await refreshActive().catch(()=>null);if(existing)return null;}setError(mediaError(value));throw value;}finally{startingRef.current=false;setChecking(false);}},[acquire,refreshActive,restore,socket]);
  const accept=useCallback(async(camera=true)=>{setError("");try{await acquire(incoming?.mediaMode==="video"&&camera);const value=await emit(socket,incoming?.invitation?"call:join":"call:accept",{callId:incoming._id,cameraEnabled:camera});setRecovery(null);setCall(value);setIncoming(null);return value;}catch(value){setError(mediaError(value));throw value;}},[acquire,incoming,socket]);
  const reject=useCallback(async()=>{try{if(incoming)await emit(socket,incoming.invitation?"call:decline-invitation":"call:reject",{callId:incoming._id||incoming.callId});}finally{setIncoming(null);setError("");}},[incoming,socket]);
  const end=useCallback(async()=>{try{if(callRef.current)await emit(socket,callRef.current.status==="ringing"?"call:cancel":"call:end",{callId:callRef.current._id});}finally{cleanup();setError("");}},[cleanup,socket]);
  const rejoin=useCallback(async()=>{if(!recovery||checking)return;setChecking(true);setError("");try{await acquire(recovery.mediaMode==="video");const value=await emit(socket,"call:rejoin",{callId:recovery._id,cameraEnabled:recovery.mediaMode==="video"});setRecovery(null);setCall(value);}catch(value){setError(value.message||"The call could not be rejoined.");await refreshActive().catch(()=>setRecovery(null));}finally{setChecking(false);}},[acquire,checking,recovery,refreshActive,socket]);
  const leaveRecovery=useCallback(async()=>{if(!recovery||checking)return;setChecking(true);try{const caller=userId(recovery.initiatedBy)===selfId,event=recovery.status==="ringing"&&caller?"call:cancel":"call:leave";await emit(socket,event,{callId:recovery._id});setRecovery(null);setError("");cleanup();}catch(value){setError(value.message||"Unable to clear the call.");await refreshActive().catch(()=>{});}finally{setChecking(false);}},[checking,cleanup,recovery,refreshActive,selfId,socket]);
  const clearError=useCallback(()=>setError(""),[]);
  const toggleMicrophone=useCallback(async()=>{const track=streamRef.current?.getAudioTracks?.()[0];if(!track)return;track.enabled=!track.enabled;await emit(socket,"media:microphone",{callId:callRef.current._id,enabled:track.enabled});setCall(current=>({...current,localMicrophoneEnabled:track.enabled}));},[socket]);
  const toggleCamera=useCallback(async()=>{let track=streamRef.current?.getVideoTracks?.()[0];if(!track){const extra=await navigator.mediaDevices.getUserMedia({video:true});track=extra.getVideoTracks()[0];streamRef.current.addTrack(track);for(const peer of peers.current.values())peer.addTrack(track,streamRef.current);setLocalStream(streamRef.current);}else track.enabled=!track.enabled;await emit(socket,"media:camera",{callId:callRef.current._id,enabled:track.enabled});setCall(current=>({...current,localCameraEnabled:track.enabled}));},[socket]);
  const shareScreen=useCallback(async()=>{if(!navigator.mediaDevices?.getDisplayMedia)throw new Error("Screen sharing is not supported by this browser.");const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false}),track=stream.getVideoTracks()[0];await emit(socket,"media:screen-start",{callId:callRef.current._id});screenRef.current=stream;for(const peer of peers.current.values()){const sender=peer.getSenders().find(value=>value.track?.kind==="video");if(sender)await sender.replaceTrack(track);else peer.addTrack(track,stream);}track.onended=()=>stopScreen().catch(()=>{});setCall(current=>({...current,screenSharing:true}));},[socket]);
  const stopScreen=useCallback(async()=>{if(!callRef.current)return;const camera=streamRef.current?.getVideoTracks?.()[0]||null;for(const peer of peers.current.values()){const sender=peer.getSenders().find(value=>value.track?.kind==="video");if(sender)await sender.replaceTrack(camera);}for(const track of screenRef.current?.getTracks?.()||[])track.stop();screenRef.current=null;await emit(socket,"media:screen-stop",{callId:callRef.current._id});setCall(current=>({...current,screenSharing:false}));},[socket]);
  const toggleHand=useCallback(async()=>{const raised=!callRef.current?.localHandRaised;await emit(socket,raised?"call:hand-raise":"call:hand-lower",{callId:callRef.current._id});setCall(current=>({...current,localHandRaised:raised}));},[socket]);
  const invite=useCallback(user=>emit(socket,"call:invite",{callId:callRef.current._id,userId:user}),[socket]);
  const selectDevice=useCallback(async(kind,deviceId)=>{if(kind==="audiooutput")return;const stream=await navigator.mediaDevices.getUserMedia({[kind==="audioinput"?"audio":"video"]:{deviceId:{exact:deviceId}}}),track=stream.getTracks()[0],old=kind==="audioinput"?streamRef.current.getAudioTracks()[0]:streamRef.current.getVideoTracks()[0];old?.stop();if(old)streamRef.current.removeTrack(old);streamRef.current.addTrack(track);for(const peer of peers.current.values()){const sender=peer.getSenders().find(value=>value.track?.kind===track.kind);if(sender)await sender.replaceTrack(track);}setLocalStream(streamRef.current);},[]);

  useEffect(()=>{if(!socket)return undefined;const onIncoming=value=>setIncoming(value),onInvitation=value=>{if(!value||String(value.callId||value._id||"")===String(callRef.current?._id||""))return;setIncoming(value);setRecovery(null);},onAccepted=async value=>{setCall(value);setIncoming(null);if(userId(value.initiatedBy)===selfId)for(const participant of value.participants||[])if(userId(participant)!==selfId&&participant.status==="joined")await offerTo(userId(participant)).catch(value=>setError(value.message));},onEnded=()=>cleanup(),onJoined=async value=>{setCall(current=>value.call||current);if(value.userId&&String(value.userId)!==selfId)await offerTo(value.userId).catch(()=>{});},onParticipants=value=>setCall(current=>value.call||current),onOffer=async value=>{const peer=await peerFor(value.from);await peer.setRemoteDescription(value.description);const answer=await peer.createAnswer();await peer.setLocalDescription(answer);await emit(socket,"webrtc:answer",{callId:value.callId,to:value.from,description:peer.localDescription});},onAnswer=async value=>(await peerFor(value.from)).setRemoteDescription(value.description),onIce=async value=>{if(value.candidate)await(await peerFor(value.from)).addIceCandidate(value.candidate);},onRevoked=()=>{setError("Your access to this call was revoked.");cleanup();};socket.on("call:incoming",onIncoming);socket.on("call:invitation",onInvitation);socket.on("call:accepted",onAccepted);socket.on("call:ended",onEnded);socket.on("call:cancelled",onEnded);socket.on("call:rejected",onEnded);socket.on("call:missed",onEnded);socket.on("call:participant-joined",onJoined);socket.on("call:participants-updated",onParticipants);socket.on("call:participant-declined",onParticipants);socket.on("call:participant-left",onParticipants);socket.on("webrtc:offer",onOffer);socket.on("webrtc:answer",onAnswer);socket.on("webrtc:ice-candidate",onIce);socket.on("call:access-revoked",onRevoked);return()=>{for(const[event,fn]of [["call:incoming",onIncoming],["call:invitation",onInvitation],["call:accepted",onAccepted],["call:ended",onEnded],["call:cancelled",onEnded],["call:rejected",onEnded],["call:missed",onEnded],["call:participant-joined",onJoined],["call:participants-updated",onParticipants],["call:participant-declined",onParticipants],["call:participant-left",onParticipants],["webrtc:offer",onOffer],["webrtc:answer",onAnswer],["webrtc:ice-candidate",onIce],["call:access-revoked",onRevoked]])socket.off(event,fn);};},[cleanup,offerTo,peerFor,selfId,socket]);
  useEffect(()=>{if(!socket)return undefined;const clearPeer=value=>{const user=String(value?.userId||"");if(!user)return;peers.current.get(user)?.close();peers.current.delete(user);pendingIceCandidatesRef.current.delete(signalKey(value.callId||value.call?._id, user));};socket.on("call:participant-left",clearPeer);return()=>socket.off("call:participant-left",clearPeer);},[signalKey,socket]);
  useEffect(()=>{refreshActive().catch(value=>setError(value.message||"Unable to check current call."));},[refreshActive]);
  useEffect(()=>{if(!socket)return undefined;const recovered=value=>{if(!callRef.current)restore(value);};socket.on("call:recovery",recovered);return()=>socket.off("call:recovery",recovered);},[restore,socket]);
  useEffect(()=>{if(!call?.answeredAt)return undefined;const started=new Date(call.answeredAt).getTime(),timer=setInterval(()=>setElapsed(Math.max(0,Math.floor((Date.now()-started)/1000))),1000);return()=>clearInterval(timer);},[call?.answeredAt]);
  useEffect(()=>{if(!socket)return undefined;const reconnect=()=>{if(callRef.current){setReconnecting(true);emit(socket,"call:rejoin",{callId:callRef.current._id}).then(value=>{setCall(value);setReconnecting(false);setError("");}).catch(()=>{setError("The call could not be recovered safely.");cleanup();});}else refreshActive().catch(()=>{});};socket.on("connect",reconnect);return()=>socket.off("connect",reconnect);},[cleanup,refreshActive,socket]);
  const value=useMemo(()=>({incoming,call,recovery,checking,localStream,remoteStreams,error,quality,devices,elapsed,reconnecting,start,refreshActive,rejoin,leaveRecovery,clearError,accept,reject,end,toggleMicrophone,toggleCamera,shareScreen,stopScreen,toggleHand,invite,selectDevice,loadDevices}),[incoming,call,recovery,checking,localStream,remoteStreams,error,quality,devices,elapsed,reconnecting,start,refreshActive,rejoin,leaveRecovery,clearError,accept,reject,end,toggleMicrophone,toggleCamera,shareScreen,stopScreen,toggleHand,invite,selectDevice,loadDevices]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
};
export const useCall=()=>useContext(Context);
