// @vitest-environment jsdom
import React from"react";import{cleanup,fireEvent,render,screen,waitFor}from"@testing-library/react";import{afterEach,beforeEach,expect,test,vi}from"vitest";import{CallProvider,useCall}from"./CallContext";
const mocks=vi.hoisted(()=>({active:vi.fn(),ice:vi.fn(),socket:null}));vi.mock("./ChatContext",()=>({useChat:()=>({socket:mocks.socket})}));vi.mock("../authContext",()=>({useAuth:()=>({currentUser:{_id:"me"}})}));vi.mock("../services/callApi",()=>({getActiveCall:mocks.active,getIceServers:mocks.ice}));
const activeCall={_id:"call1",callType:"repository",mediaMode:"audio",status:"active",startedAt:"2026-07-18T10:00:00Z",initiatedBy:"me",participants:[{user:{_id:"me"},status:"joined"}]};
function Probe(){const call=useCall();return <div><span data-testid="recovery">{call.recovery?._id||"none"}</span><span data-testid="current">{call.call?._id||"none"}</span><button onClick={call.rejoin}>rejoin</button><button onClick={call.leaveRecovery}>leave</button><button disabled={call.checking} onClick={()=>call.start({callType:"repository",repositoryId:"repo1",mediaMode:"audio"})}>start</button></div>;}
beforeEach(()=>{const handlers={};mocks.socket={connected:true,on:vi.fn((event,fn)=>{handlers[event]=fn;}),off:vi.fn(),emit:vi.fn((event,payload,ack)=>{if(event==="call:rejoin")ack?.({success:true,call:activeCall});else if(event==="call:leave")ack?.({success:true,call:{...activeCall,status:"ended"}});else if(event==="call:initiate")ack?.({success:true,call:{...activeCall,_id:"new-call"}});})};mocks.ice.mockResolvedValue({iceServers:[]});Object.defineProperty(navigator,"mediaDevices",{configurable:true,value:{getUserMedia:vi.fn(async()=>({getTracks:()=>[{stop:vi.fn()}],getAudioTracks:()=>[],getVideoTracks:()=>[]})),enumerateDevices:vi.fn(async()=>[])}});});afterEach(()=>{cleanup();vi.clearAllMocks();});
test("refresh restores a visible active call and Leave clears it",async()=>{mocks.active.mockResolvedValue({call:activeCall});render(<CallProvider><Probe/></CallProvider>);expect(await screen.findByText("call1")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"leave"}));await waitFor(()=>expect(screen.getByTestId("recovery").textContent).toBe("none"));expect(mocks.socket.emit).toHaveBeenCalledWith("call:leave",{callId:"call1"},expect.any(Function));});
test("Rejoin restores media call state after refresh",async()=>{mocks.active.mockResolvedValue({call:activeCall});render(<CallProvider><Probe/></CallProvider>);await screen.findByText("call1");fireEvent.click(screen.getByRole("button",{name:"rejoin"}));await waitFor(()=>expect(screen.getByTestId("current").textContent).toBe("call1"));expect(navigator.mediaDevices.getUserMedia).toHaveBeenCalled();});
test("start checks reconciled state and repeated clicks create only one call",async()=>{mocks.active.mockResolvedValue({call:null});render(<CallProvider><Probe/></CallProvider>);await waitFor(()=>expect(screen.getByTestId("recovery").textContent).toBe("none"));const button=screen.getByRole("button",{name:"start"});fireEvent.click(button);fireEvent.click(button);await waitFor(()=>expect(screen.getByTestId("current").textContent).toBe("new-call"));expect(mocks.socket.emit.mock.calls.filter(([event])=>event==="call:initiate")).toHaveLength(1);});
