import React, { useCallback, useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import Navbar from "../Navbar";
import { actionRequest, formatDuration, statusLabel, terminalStatuses } from "./actionApi";
import "./actions.css";

const WorkflowRunPage = () => {
  const { id, runId } = useParams(); const navigate = useNavigate();
  const [state, setState] = useState({ loading: true, error: "", run: null, logs: [], canManage: false, runnerMode: "mock" }); const [busy, setBusy] = useState(false); const [openJobs, setOpenJobs] = useState({}); const [openSteps, setOpenSteps] = useState({});
  const load = useCallback(async (signal) => { try { const [detail, logs] = await Promise.all([actionRequest(`/repo/${id}/actions/runs/${runId}`, { signal }), actionRequest(`/repo/${id}/actions/runs/${runId}/logs`, { signal })]); setState({ loading: false, error: "", run: detail.run, logs: logs.logs || [], canManage: Boolean(detail.canManage), runnerMode: detail.runnerMode }); } catch (error) { if (error.name !== "AbortError") setState((current) => ({ ...current, loading: false, error: error.message })); } }, [id, runId]);
  useEffect(() => { const controller = new AbortController(); load(controller.signal); return () => controller.abort(); }, [load]);
  useEffect(() => { if (!state.run || terminalStatuses.has(state.run.status)) return undefined; const tick = () => { if (document.visibilityState === "visible") load(); }; const timer = window.setInterval(tick, 3000); document.addEventListener("visibilitychange", tick); return () => { clearInterval(timer); document.removeEventListener("visibilitychange", tick); }; }, [load, state.run]);
  const action = async (name) => { if (name === "cancel" && !window.confirm("Cancel this workflow run?")) return; setBusy(true); try { const data = await actionRequest(`/repo/${id}/actions/runs/${runId}/${name}`, { method: "POST" }); if (name === "rerun") navigate(`/repo/${id}/actions/runs/${data.run._id}`); else await load(); } catch (error) { setState((current) => ({ ...current, error: error.message })); } finally { setBusy(false); } };
  if (state.loading) return <div className="actions-page"><Navbar /><main className="actions-shell"><div className="actions-state">Loading workflow run...</div></main></div>;
  if (!state.run) return <div className="actions-page"><Navbar /><main className="actions-shell"><div className="actions-state actions-state--error">{state.error || "Workflow run not found"}</div></main></div>;
  const run = state.run; const logJobs = new Map(state.logs.map((job) => [String(job.jobId), job]));
  return <div className="actions-page"><Navbar /><main className="actions-shell"><p><Link to={`/repo/${id}/actions`}>← Actions</Link></p>{state.error && <div className="actions-state actions-state--error" role="alert">{state.error}</div>}
    <header className="actions-detail-header"><div><span className={`actions-status is-${run.status}`}>{statusLabel(run.status)}</span><h1>{run.workflowName} <small>#{run.attempt}</small></h1><p>Branch: <strong>{run.branch}</strong> · Commit: <code>{run.commitHash.slice(0, 12)}</code> · Event: {run.trigger}</p><p>Triggered by {run.actor?.username || "Deleted user"} · {formatDuration(run.durationMs)}</p></div>{state.canManage && <div>{["queued", "running"].includes(run.status) && <button className="actions-danger" disabled={busy} onClick={() => action("cancel")}>Cancel workflow</button>}{terminalStatuses.has(run.status) && <button className="actions-primary" disabled={busy} onClick={() => action("rerun")}>Rerun workflow</button>}</div>}</header>
    {state.runnerMode === "mock" && <div className="actions-mock-warning" role="status">Safe mock runner: requested commands are recorded but not executed.</div>}
    <section className="actions-jobs" aria-live="polite"><h2>Jobs</h2>{(run.jobs || []).map((job) => { const opened = openJobs[job._id] !== false; const logs = logJobs.get(String(job._id)); return <article key={job._id}><button className="actions-job-toggle" aria-expanded={opened} onClick={() => setOpenJobs((current) => ({ ...current, [job._id]: !opened }))}><span>{statusLabel(job.status)}</span><strong>{job.name}</strong><small>{formatDuration(job.durationMs)}</small></button>{opened && <ol>{job.steps.map((step) => { const expanded = Boolean(openSteps[step._id]); const log = logs?.steps?.find((item) => String(item.stepId) === String(step._id))?.log || step.logPreview || ""; return <li key={step._id}><button aria-expanded={expanded} onClick={() => setOpenSteps((current) => ({ ...current, [step._id]: !expanded }))}><span>{statusLabel(step.status)}</span><strong>{step.name}</strong><small>{formatDuration(step.durationMs)}</small></button>{expanded && <div className="actions-log"><p><code>{step.command}</code></p><pre role="region" aria-label={`${step.name} logs`}>{log || "Logs are not available yet."}</pre></div>}</li>; })}</ol>}</article>; })}</section>
  </main></div>;
};
export default WorkflowRunPage;
